### ISSUE TITLE
Resolving relative ref does not work on Gitlab

### ISSUE THREAD

**Issue by Apoorva64** [microcks/microcks#1032]
### Describe the bug

When importing an OpenApi from gitlab the relative refs are not resolved. Which resukts in an incomplete API definition 

### Expected behavior

The relative ref should resolve

### Actual behavior

The Importer Job fails to fetch a file that exists

### How to Reproduce?

1.  create an importer job with this url: https://gitlab.com/api/v4/projects/53580286/repository/files/full-exemple%2Fopenapi.yaml/raw?head=main
2. run the job

You will obtain 
```
microcks                                   | 08:54:37.947  INFO 1 --- [080-exec-3] i.github.microcks.service.JobService     : Starting import for job 'full-exemple-test-gitlab'
microcks                                   | 08:54:37.947  INFO 1 --- [080-exec-3] i.g.microcks.service.ServiceService      : Importing service definitions from https://gitlab.com/api/v4/projects/53580286/repository/files/full-exemple%2Fopenapi.yaml/raw?head=main
microcks                                   | 08:54:38.256 DEBUG 1 --- [080-exec-3] g.m.u.RelativeReferenceURLBuilderFactory : Found a GitLab File specific header, returning a GitLabReferenceURLBuilder
microcks                                   | 08:54:38.256  INFO 1 --- [080-exec-3] i.g.m.u.MockRepositoryImporterFactory    : Found an openapi: 3 pragma in file so assuming it's an OpenAPI spec to import
microcks                                   | 08:54:38.257  INFO 1 --- [080-exec-3] i.g.microcks.util.ReferenceResolver      : Downloading a reference file at https://gitlab.com/api/v4/projects/53580286/repository/files/full-exemple%2Fpaths%2Fowner@{owner}@car%2Fpath.yaml/raw?head=main
microcks                                   | 08:54:38.421 ERROR 1 --- [080-exec-3] i.g.m.u.AbstractJsonRepositoryImporter   : IOException while trying to resolve reference paths/owner@{owner}@car/path.yaml
microcks                                   | 
microcks                                   | java.io.FileNotFoundException: https://gitlab.com/api/v4/projects/53580286/repository/files/full-exemple%2Fpaths%2Fowner@{owner}@car%2Fpath.yaml/raw?head=main
microcks                                   |    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1996)
microcks                                   |    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
microcks                                   |    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
microcks                                   |    at io.github.microcks.util.HTTPDownloader.handleHTTPDownloadToFile(HTTPDownloader.java:138)
microcks                                   |    at io.github.microcks.util.ReferenceResolver.getHttpReferenceContent(ReferenceResolver.java:105)
microcks                                   |    at io.github.microcks.util.AbstractJsonRepositoryImporter.initializeExternalReferences(AbstractJsonRepositoryImporter.java:119)
microcks                                   |    at io.github.microcks.util.openapi.OpenAPIImporter.getServiceDefinitions(OpenAPIImporter.java:106)
microcks                                   |    at io.github.microcks.service.ServiceService.importServiceDefinition(ServiceService.java:176)
microcks                                   |    at io.github.microcks.service.ServiceService.importServiceDefinition(ServiceService.java:150)
microcks                                   |    at io.github.microcks.service.JobService.doImportJob(JobService.java:70)
microcks                                   |    at io.github.microcks.web.JobController.startJob(JobController.java:171)
microcks                                   |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
microcks                                   |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
microcks                                   |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
microcks                                   |    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
microcks                                   |    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
microcks                                   |    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
microcks                                   |    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
microcks                                   |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
microcks                                   |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
microcks                                   |    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
microcks                                   |    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
microcks                                   |    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
microcks                                   |    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
microcks                                   |    at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:925)
microcks                                   |    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:593)
microcks                                   |    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
microcks                                   |    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
microcks                                   |    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
microcks                                   |    at io.github.microcks.web.filter.CorsFilter.doFilter(CorsFilter.java:49)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
microcks                                   |    at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:340)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:82)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:128)
microcks                                   |    at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
microcks                                   |    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
microcks                                   |    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
microcks                                   |    at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)
microcks                                   |    at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
microcks                                   |    at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
microcks                                   |    at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
microcks                                   |    at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
microcks                                   |    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
microcks                                   |    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
microcks                                   |    at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
microcks                                   |    at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
microcks                                   |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
microcks                                   |    at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
microcks                                   |    at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
microcks                                   |    at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
microcks                                   |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
microcks                                   |    at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
microcks                                   |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224)
microcks                                   |    at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
microcks                                   |    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
microcks                                   |    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
microcks                                   |    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
microcks                                   |    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
microcks                                   |    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
microcks                                   |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
microcks                                   |    at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
microcks                                   |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
microcks                                   |    at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
microcks                                   |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
microcks                                   |    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
microcks                                   |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
microcks                                   |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
microcks                                   |    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
microcks                                   |    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
microcks                                   |    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
microcks                                   |    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
microcks                                   |    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
microcks                                   |    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
microcks                                   |    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:738)
microcks                                   |    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
microcks                                   |    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
microcks                                   |    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
microcks                                   |    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
microcks                                   |    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
microcks                                   |    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
microcks                                   |    at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
microcks                                   |    at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
microcks                                   |    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
microcks                                   |    at java.base/java.lang.Thread.run(Thread.java:840)
microcks                                   | 
microcks                                   | 08:54:38.422  INFO 1 --- [080-exec-3] i.g.m.u.AbstractJsonRepositoryImporter   : Ignoring the reference paths/owner@{owner}@car/path.yaml cause it could not be resolved
microcks                                   | 08:54:38.423 DEBUG 1 --- [080-exec-3] i.g.microcks.service.ServiceService      : Service [OpenAPI Car API, 1.0.0] exists ? false
microcks                                   | 08:54:38.426 DEBUG 1 --- [080-exec-3] i.g.microcks.service.ServiceService      : Service change event has been published
microcks                                   | 08:54:38.427 DEBUG 1 --- [   task-13] i.g.m.l.TestConformanceMetricConfigurer  : Received a ServiceChangeEvent on 6597c3ce87ff5239a4b0634a
microcks                                   | 08:54:38.427  INFO 1 --- [080-exec-3] i.g.microcks.service.ServiceService      : Having imported 1 services definitions into repository
microcks                                   | 08:54:38.427  INFO 1 --- [080-exec-3] i.github.microcks.service.JobService     : Import of job 'full-exemple-test-gitlab' done
```

### Microcks version or git rev

quay.io/microcks/microcks:nightly@sha256:1aaa5b11d50500cf32fda63dd5198cb3d615fee669f9eb62a5d71a1857222bb5

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

### Additional information
When you go to the url: https://gitlab.com/api/v4/projects/53580286/repository/files/full-exemple%2Fpaths%2Fowner@{owner}@car%2Fpath.yaml/raw?head=main it works but idk why microcks can't fetch it

**Comment by lbroudoux** [comment]
Thanks for the detailed illustration. I succeed in reproducing it. Will work on it now.

**Comment by Apoorva64** [comment]
@lbroudoux Would it be possible to have a repository on gitlab where we would store gitlab tests samples. so that we could add them to microcks tests in the code>?
This way if gitlab changes headers again for exemples we would know

**Comment by lbroudoux** [comment]
Yes, that's what I'm doing at the moment ;-) I think we need to introduce this in unit test suite.

**Comment by lbroudoux** [comment]
The first downloading error (on https://gitlab.com/api/v4/projects/53580286/repository/files/full-exemple%2Fpaths%2Fowner@{owner}@car%2Fpath.yaml/raw?head=main) is due to incorrect URL encoding and is easy to fix.

The second one (on https://gitlab.com/api/v4/projects/53580286/repository/files/full-exemple%2Fpaths%2Fowner@%7Bowner%7D@car%2Fget%2F200%2Fresponse.yaml/raw?head=main) is a bit trickier as the reference (`get/200/response.yaml`) does not start with `./` or `../` and so the URL builder consider it as relative to the root that is https://gitlab.com/api/v4/projects/53580286/repository/files/full-exemple and not https://gitlab.com/api/v4/projects/53580286/repository/files/full-exemple%2Fpaths%2Fowner@{owner}@car ...

Working on it!

**Comment by lbroudoux** [comment]
I've got something working! 🎉 
I was wondering if you would be OK with reusing your sample repo resources as an official test suite. I've gone through your sample and I've never seen something decomposed to that level 😅 
I can imagine people saying "OpenAPI is hard" is they through stuffs like that 🤣

**Comment by Apoorva64** [comment]
Yes you can use it.
OpenApi is hard to maintain at scale. My work at Orange consisted of using microcks in complex and large API(over 5k lines of swagger) that required that architecture to be readable.

**Comment by lbroudoux** [comment]
CI/CD pipeline is OK!
