### ISSUE TITLE
Server Error Encountered  Apicurio Microcks integration

### ISSUE THREAD

**Issue by buaydin** [microcks/microcks#1084]
### Describe the bug

We follow the documentation from; 
https://www.apicur.io/studio/docs/integrate-microcks-for-mocking-your-api
We are able see Api Mocking section but when we are trying to create a mock for API apicurio it thows an error;

`io.apicurio.hub.core.exceptions.ServerError: Unexpected server error
	at io.apicurio.hub.api.rest.impl.DesignsResource.mockApi(DesignsResource.java:933)
	at io.apicurio.hub.api.rest.impl.DesignsResource_ClientProxy.mockApi(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
	at io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:35)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.hub.api.security.QuarkusAuthenticationFilter.doFilter(QuarkusAuthenticationFilter.java:83)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.hub.api.filters.DisableCachingFilter.doFilter(DisableCachingFilter.java:66)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.hub.api.filters.CorsFilter.doFilter(CorsFilter.java:64)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:602)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:120)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:284)
	at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:417)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.apicurio.hub.api.microcks.MicrocksConnectorException: Unexpected response by Microcks server: 
	at io.apicurio.hub.api.microcks.MicrocksConnector.uploadResourceContent(MicrocksConnector.java:171)
	at io.apicurio.hub.api.microcks.MicrocksConnector_ClientProxy.uploadResourceContent(Unknown Source)
	at io.apicurio.hub.api.rest.impl.DesignsResource.mockApi(DesignsResource.java:905)
	... 74 more` 

I can see;
microcks-app 
microcks-app-js 
microcks-serviceaccount

Clients enabled, microcks-serviceaccount's clientSecret is true. Is there a bug or am I missing something?

### How to Reproduce?

Create an api, after than Create  a mock
![image](https://github.com/microcks/microcks/assets/126671687/7d857ea5-5f51-4d65-ba47-4ba0364e7bb6)

### Microcks version or git rev

1.8.1 helm chart

**Comment by lbroudoux** [comment]
Hi,

The error may come from missing privileges on the `microcks-serviceaccount` SA. By default, and as explained [here](https://microcks.io/documentation/automating/service-account/#inspecting-default-service-account) the default service account has only the `user` role. To import artifacts and create mock, a user must also have the `manager` role. You may add this role from the `microcks-app` resource to the default service account or create a new dedicated service account with this role for Apicurio.

Let us know if it helps.

**Comment by lbroudoux** [comment]
Seems good... 🤔  Any logs on microcks server side to help with the kind of error?

**Comment by buaydin** [comment]
There is no error logs related to this on pod logs. But from Chrome Inspect I see an error;
![image](https://github.com/microcks/microcks/assets/126671687/5234b971-eca3-4a43-bdfd-ee698daccc1d)

There is an internal server error.

**Comment by lbroudoux** [comment]
Yes but this error is coming from the Apicurio side. We should be able to get logs as your browser is calling the Apicurio api server that in turns calls the Microcks server.

**Comment by buaydin** [comment]
I see @lbroudoux But there are no logs on microcks pods when this issue occurs  :(

**Comment by buaydin** [comment]
@lbroudoux  any suggestions for troubleshooting?

**Comment by lbroudoux** [comment]
I had a look at the code and it looks like Apicurio receives an unexpected return code from Microcks...

**Comment by buaydin** [comment]
Hi @lbroudoux  I switched to TRACE logs instead of INFO Log in microcks All I can see these lines when creating a mock;

08:45:37.831 [TRACE] io.github.microcks.security.MicrocksJwtConverter dt.trace_sampled: true, dt.trace_id: e93b8916ccb6289d813e715c3442972c, dt.entity.process_group_instance: PROCESS_GROUP_INSTANCE-D17AD28AF88DBA53, dt.span_id: 7bf16c3ed068f6e9, dt.entity.host: HOST-AFB867879E3CB381 - JWT extracted roles for microcks-app: [user]
08:45:41.085 [TRACE] io.github.microcks.web.HealthController dt.trace_sampled: true, dt.trace_id: 8b8e1d4e76ca03ca7da830db7bc2f324, dt.entity.process_group_instance: PROCESS_GROUP_INSTANCE-D17AD28AF88DBA53, dt.span_id: 8e508b5811f6e9f3, dt.entity.host: HOST-AFB867879E3CB381 - Health check endpoint invoked
08:45:41.086 [TRACE] io.github.microcks.web.HealthController dt.trace_sampled: true, dt.trace_id: 3ca4633fef74d3cef2f8a26fd1af427b, dt.entity.process_group_instance: PROCESS_GROUP_INSTANCE-D17AD28AF88DBA53, dt.span_id: 5c1f14e23482ab52, dt.entity.host: HOST-AFB867879E3CB381 - Health check endpoint invoked
08:45:41.090 [TRACE] io.github.microcks.web.HealthController dt.trace_sampled: true, dt.trace_id: 8b8e1d4e76ca03ca7da830db7bc2f324, dt.entity.process_group_instance: PROCESS_GROUP_INSTANCE-D17AD28AF88DBA53, dt.span_id: 8e508b5811f6e9f3, dt.entity.host: HOST-AFB867879E3CB381 - Health check is OK
08:45:41.091 [TRACE] io.github.microcks.web.HealthController dt.trace_sampled: true, dt.trace_id: 3ca4633fef74d3cef2f8a26fd1af427b, dt.entity.process_group_instance: PROCESS_GROUP_INSTANCE-D17AD28AF88DBA53, dt.span_id: 5c1f14e23482ab52, dt.entity.host: HOST-AFB867879E3CB381 - Health check is OK
08:45:51.076 [TRACE] io.github.microcks.web.HealthController dt.trace_sampled: true, dt.trace_id: 3dfccec0e7eb66bb4be91603527b137b, dt.entity.process_group_instance: PROCESS_GROUP_INSTANCE-D17AD28AF88DBA53, dt.span_id: 40925ffb0c699738, dt.entity.host: HOST-AFB867879E3CB381 - Health check endpoint invoked
08:45:51.076 [TRACE] io.github.microcks.web.HealthController dt.trace_sampled: true, dt.trace_id: 412a6b7bb30a5188750d554a0282ed2c, dt.entity.process_group_instance: PROCESS_GROUP_INSTANCE-D17AD28AF88DBA53, dt.span_id: 3f0d6346467d77f0, dt.entity.host: HOST-AFB867879E3CB381 - Health check endpoint invoked
08:45:51.080 [TRACE] io.github.microcks.web.HealthController dt.trace_sampled: true, dt.trace_id: 3dfccec0e7eb66bb4be91603527b137b, dt.entity.process_group_instance: PROCESS_GROUP_INSTANCE-D17AD28AF88DBA53, dt.span_id: 40925ffb0c699738, dt.entity.host: HOST-AFB867879E3CB381 - Health check is OK
08:45:51.081 [TRACE] io.github.microcks.web.HealthController dt.trace_sampled: true, dt.trace_id: 412a6b7bb30a5188750d554a0282ed2c, dt.entity.process_group_instance: PROCESS_GROUP_INSTANCE-D17AD28AF88DBA53, dt.span_id: 3f0d6346467d77f0, dt.entity.host: HOST-AFB867879E3CB381 - Health check is OK

**Comment by lbroudoux** [comment]
Hello,
So if these are the trace corresponding to the Apicurio call, you can see this line:

JWT extracted roles for microcks-app: [user]

That let us know that the token associated with the call only has the user role and not the manager one that is required for creating mock. Could you check your service account settings?

**Comment by buaydin** [comment]
But this user has admin and manager roles :(
![image](https://github.com/microcks/microcks/assets/126671687/c0aef19a-f126-497e-b261-8282ed31aa57)

**Comment by lbroudoux** [comment]
Are you sure that these are resource-scoped roles and not realm roles? Some releases ago, we switched from realm-scoped roles to resource-scope roles. The `user` and `manager` roles are now attached to the `microcks-app` client/application.

**Comment by buaydin** [comment]
I fixed the issue with adding Client Roles to microcks-app.
![image](https://github.com/microcks/microcks/assets/126671687/2228e6c7-c7e3-490c-a7ea-3e57423760b1)

**Comment by buaydin** [comment]
I fixed the issue with adding Client Roles from Default Roles to microcks-app.
