### ISSUE TITLE
Import of AsyncAPI 2.x specs with missing parameter examples is failing

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1114]
### Describe the bug

When importing an AsyncAPI 2.x spec with missing examples for a parameter definition, Microcks throws an exception, complaining that parameters are null. This was not the case before (aka in `1.8.1`).

### Expected behavior

This should silently fail - obviously parameter will not be imported but at least the remaining part of the import should be ok.

### Actual behavior

```
10:29:36.592 ERROR 49780 --- [80-exec-10] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "parameters" is null] with root cause

java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "parameters" is null
        at io.github.microcks.util.URIBuilder.buildURIFromPattern(URIBuilder.java:82)
        at io.github.microcks.util.asyncapi.AsyncAPIImporter.getMessageDefinitions(AsyncAPIImporter.java:289)
        at io.github.microcks.service.ServiceService.importServiceDefinition(ServiceService.java:279)
        at io.github.microcks.web.UploadArtifactController.importArtifact(UploadArtifactController.java:114)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

### Microcks version or git rev

nightly - 1.9.x

**Comment by lbroudoux** [comment]
This is a consequence of #1016 as guard protections on parameters have been removed when introducing Multimap support.
