### ISSUE TITLE
gRPC tests on insecure endpoints no longer work

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1198]
### Describe the bug

When launching a test on insecure gRPC endpoints, the test keep running in the UI until the timeout is reached and finished incomplete. 

### Expected behavior

The test of insecure gRPC endpoint should work with a test that complete (success or failure) and no errors in the logs.

### Actual behavior

On the microcks logs, we can see this stack trace:

```
09:56:58.247 DEBUG 3704 --- [080-exec-7] i.github.microcks.web.TestController     : Creating new test for 66694c22d9bf0f51e1647dfc on endpoint http://localhost:9090
09:56:58.267 DEBUG 3704 --- [080-exec-7] i.g.microcks.service.TestService         : Calling launchTestsInternal() marked as Async
09:56:58.270 DEBUG 3704 --- [080-exec-7] i.g.microcks.service.TestService         : Async launchTestsInternal() as now finished
09:56:58.274 DEBUG 3704 --- [    task-1] i.g.m.service.TestRunnerService          : No Test Secret or no CA Cert found, installing accept everything strategy
09:56:58.283 DEBUG 3704 --- [    task-1] i.g.m.util.grpc.GrpcTestRunner           : Launching test run on http://localhost:9090 for 2 request(s)
09:56:58.299 DEBUG 3704 --- [080-exec-8] i.github.microcks.web.TestController     : Getting TestResult with id 666954ca955e6a159917e813
09:56:58.300 ERROR 3704 --- [    task-1] i.g.m.service.TestRunnerService          : Throwable while testing operation greeting

java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "creds" is null
        at io.grpc.netty.shaded.io.grpc.netty.ProtocolNegotiators.from(ProtocolNegotiators.java:159)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.newChannelBuilder(NettyChannelProvider.java:50)
        at io.grpc.ManagedChannelRegistry.newChannelBuilder(ManagedChannelRegistry.java:195)
        at io.grpc.ManagedChannelRegistry.newChannelBuilder(ManagedChannelRegistry.java:155)
        at io.grpc.Grpc.newChannelBuilder(Grpc.java:101)
        at io.grpc.Grpc.newChannelBuilderForAddress(Grpc.java:111)
        at io.github.microcks.util.grpc.GrpcTestRunner.runTest(GrpcTestRunner.java:139)
        at io.github.microcks.util.grpc.GrpcTestRunner.runTest(GrpcTestRunner.java:61)
        at io.github.microcks.service.TestRunnerService.launchTestsInternal(TestRunnerService.java:211)
```

### How to Reproduce?

1. Load the gRPC Hello World sample
2. Run a test on the mocks endpoint itself

### Microcks version or git rev

nightly and earlier

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

All methods

**Comment by lbroudoux** [comment]
It appears that `grpc-java` has changed its internal behavior. Launching a test on an insecure endpoint was previously done by building a channel like this:
```java
channel = Grpc .newChannelBuilderForAddress(endpoint.getHost(), endpoint.getPort(), null)
               .usePlainText();
               .build();
````

The 3rd argument is actually the channel `creds` that is null in the context of insecure (http only) channel.

Since `grpc-java` version ?, it has now to be created that way using an `InsecureChannelCredentials`:

```java
channel = Grpc
               .newChannelBuilderForAddress(endpoint.getHost(), endpoint.getPort(), InsecureChannelCredentials.create())
               .build();
```

The `usePlainText()` should be removed - otherwise we face this exception:
```
java.lang.IllegalStateException: Cannot change security when using ChannelCredentials
        at com.google.common.base.Preconditions.checkState(Preconditions.java:512)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.negotiationType(NettyChannelBuilder.java:337)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.usePlaintext(NettyChannelBuilder.java:463)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.usePlaintext(NettyChannelBuilder.java:75)
        at io.github.microcks.util.grpc.GrpcTestRunner.runTest(GrpcTestRunner.java:142)
```

**Comment by lbroudoux** [comment]
As we have no integration/unit tests to detect this regression, we should also absolutely provide a new one to remove this kind of failure in the future.
