### ISSUE TITLE
Cannot match any routes

### ISSUE THREAD

**Issue by RadekDvorak** [microcks/microcks#1221]
### Describe the bug

When i click the "Preferences" link in account's top-right dropdown, nothing happens.

### Expected behavior

I expect to see the account's preferences UI. 

### Actual behavior

Browser's console displays this:
```
Navigation start event: {"id":2,"url":"/0","navigationTrigger":"popstate","restoredState":null}
main.94278642350bb1b9b434.js:1 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: '0'
Error: Cannot match any routes. URL Segment: '0'
    at e.noMatchError (main.94278642350bb1b9b434.js:1:1973649)
    at t.selector (main.94278642350bb1b9b434.js:1:1973308)
    at t.error (main.94278642350bb1b9b434.js:1:1939646)
    at t._error (main.94278642350bb1b9b434.js:1:951789)
    at t.error (main.94278642350bb1b9b434.js:1:951483)
    at t._error (main.94278642350bb1b9b434.js:1:951789)
    at t.error (main.94278642350bb1b9b434.js:1:951483)
    at t._error (main.94278642350bb1b9b434.js:1:951789)
    at t.error (main.94278642350bb1b9b434.js:1:951483)
    at t._error (main.94278642350bb1b9b434.js:1:1938194)
    at T (polyfills.c63de434ec8394470f2f.js:1:14193)
    at T (polyfills.c63de434ec8394470f2f.js:1:13731)
    at polyfills.c63de434ec8394470f2f.js:1:15031
    at e.invokeTask (polyfills.c63de434ec8394470f2f.js:1:8484)
    at Object.onInvokeTask (main.94278642350bb1b9b434.js:1:1097017)
    at e.invokeTask (polyfills.c63de434ec8394470f2f.js:1:8405)
    at t.runTask (polyfills.c63de434ec8394470f2f.js:1:3662)
    at g (polyfills.c63de434ec8394470f2f.js:1:10775)
    at t.invokeTask (polyfills.c63de434ec8394470f2f.js:1:9620)
    at i.useG.invoke (polyfills.c63de434ec8394470f2f.js:1:9482)
```

### How to Reproduce?

1. Run `./run-microcks.sh dev` in the `install/podman-compose` directory
2. Open `http://127.0.0.1:8080` in your browser
3. Click on top-right "Anonymous admin", select "preferences" in the dropdown menu

### Microcks version or git rev

928a67f4c16b4f3a312129e67063e1ed39a311b1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

podman-compose

### Additional information

- I have experiences the same running microcks in k8s. Microcks version was 1.9.1 there.
- Both Chrome nad Firefox exhibit this behaviour.

**Comment by lbroudoux** [comment]
Hello,
Thank you for opening this one. This is actually a remainder from old times when we skipped this update during a Kecyloak upgrade. This should have been fixed now and will be available in `nightly` container images pretty soon.

**Comment by lbroudoux** [comment]
Hi @RadekDvorak 
Any chance you can confirm the fix is OK on your side? Be sure to pull a fresh `nightly` image.

**Comment by RadekDvorak** [comment]
OK. I will test the fix after the weekend.

**Comment by lbroudoux** [comment]
Please re-open if something goes wrong but the tests were ok on my side.
