### ISSUE TITLE
Templating functions are not available on Uber native distrib

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1226]
### Describe the bug

Microcks fails when using templating functions using the `microcks-uber:1.9.1-native` container image.

### Expected behavior

Templating functions should work whatever the distributionon.

### Actual behavior

We found the following stack traces on the server side. That is probably due to the dynamic invocation nature of templating. GraalVM native compilation need to we tweaked a bit more to support this.

When calling the `randomInt()` function:

```
09:33:33.770 ERROR 1 --- [executor-2] i.g.m.util.el.ExpressionParser           : Exception while instantiating the functionClazz class io.github.microcks.util.el.function.RandomIntELFunction

java.lang.InstantiationException: io.github.microcks.util.el.function.RandomIntELFunction
	at java.base@17.0.10/java.lang.Class.newInstance(DynamicHub.java:639)
	at io.github.microcks.util.el.ExpressionParser.doParseSimpleExpression(ExpressionParser.java:183)
	at io.github.microcks.util.el.ExpressionParser.doParseExpression(ExpressionParser.java:128)
	at io.github.microcks.util.el.ExpressionParser.parseExpressions(ExpressionParser.java:89)
	at io.github.microcks.util.el.TemplateEngine.getValue(TemplateEngine.java:67)
	at io.github.microcks.web.MockControllerCommons.unguardedRenderResponseContent(MockControllerCommons.java:264)
	at io.github.microcks.web.MockControllerCommons.renderResponseContent(MockControllerCommons.java:183)
	at io.github.microcks.web.GrpcServerCallHandler$MockedUnaryMethod.manageResponseTransmission(GrpcServerCallHandler.java:309)
	at io.github.microcks.web.GrpcServerCallHandler$MockedUnaryMethod.invoke(GrpcServerCallHandler.java:204)
	at io.github.microcks.web.GrpcServerCallHandler$MockedUnaryMethod.invoke(GrpcServerCallHandler.java:114)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:838)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
Caused by: java.lang.NoSuchMethodException: io.github.microcks.util.el.function.RandomIntELFunction.<init>()
```

When calling the ` request.body/name ` variable expression:

```
09:33:33.771  WARN 1 --- [executor-2] i.g.m.u.e.VariableReferenceExpression    : body property was requested on class io.github.microcks.util.el.EvaluableRequest but cannot find a valid getter

java.lang.NoSuchMethodException: io.github.microcks.util.el.EvaluableRequest.getBody()
	at java.base@17.0.10/java.lang.Class.checkMethod(DynamicHub.java:1040)
	at java.base@17.0.10/java.lang.Class.getMethod(DynamicHub.java:1025)
	at io.github.microcks.util.el.VariableReferenceExpression.getProperty(VariableReferenceExpression.java:180)
	at io.github.microcks.util.el.VariableReferenceExpression.getValue(VariableReferenceExpression.java:114)
	at io.github.microcks.util.el.TemplateEngine.getValue(TemplateEngine.java:72)
	at io.github.microcks.web.MockControllerCommons.unguardedRenderResponseContent(MockControllerCommons.java:264)
	at io.github.microcks.web.MockControllerCommons.renderResponseContent(MockControllerCommons.java:183)
	at io.github.microcks.web.GrpcServerCallHandler$MockedUnaryMethod.manageResponseTransmission(GrpcServerCallHandler.java:309)
	at io.github.microcks.web.GrpcServerCallHandler$MockedUnaryMethod.invoke(GrpcServerCallHandler.java:204)
	at io.github.microcks.web.GrpcServerCallHandler$MockedUnaryMethod.invoke(GrpcServerCallHandler.java:114)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:838)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
```

### How to Reproduce?

Run the Getting Started guide with a native image

### Microcks version or git rev

All

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

All

**Comment by lbroudoux** [comment]
Now fixed!
