### ISSUE TITLE
gRCP testing fails with the Uber native image

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1227]
### Describe the bug

When launching a `GRPC_PROTOBUF` test from a Uber native container image, test is failing and no request is actually issued to the tested endpoint.

### Expected behavior

Test should run correctly, at least requests should be sent to the target endpoints 😉 

### Actual behavior

We saw these stack trace on the server side - probably a consequence of incomplete reflection configuration when producing native image with GraalVM:

```
14:03:44.482 ERROR 1 --- [   task-10] i.g.m.service.TestRunnerService          : Throwable while testing operation getPets

java.lang.ExceptionInInitializerError: null
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.getSupportedSocketAddressTypes(NettyChannelProvider.java:60)
	at io.grpc.ManagedChannelRegistry.newChannelBuilder(ManagedChannelRegistry.java:186)
	at io.grpc.ManagedChannelRegistry.newChannelBuilder(ManagedChannelRegistry.java:155)
	at io.grpc.Grpc.newChannelBuilder(Grpc.java:101)
	at io.grpc.Grpc.newChannelBuilderForAddress(Grpc.java:111)
	at io.github.microcks.util.grpc.GrpcTestRunner.runTest(GrpcTestRunner.java:142)
	at io.github.microcks.util.grpc.GrpcTestRunner.runTest(GrpcTestRunner.java:61)
	at io.github.microcks.service.TestRunnerService.launchTestsInternal(TestRunnerService.java:211)
	at java.base@17.0.10/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
	at org.springframework.util.concurrent.FutureUtils.lambda$toSupplier$0(FutureUtils.java:74)
	at java.base@17.0.10/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:838)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
Caused by: java.lang.IllegalArgumentException: Class NioSocketChannel does not have a public non-arg constructor
	at io.grpc.netty.shaded.io.netty.channel.ReflectiveChannelFactory.<init>(ReflectiveChannelFactory.java:36)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:85)
	... 21 common frames omitted
Caused by: java.lang.NoSuchMethodException: io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.<init>()
	at java.base@17.0.10/java.lang.Class.checkMethod(DynamicHub.java:1040)
	at java.base@17.0.10/java.lang.Class.getConstructor0(DynamicHub.java:1206)
	at java.base@17.0.10/java.lang.Class.getConstructor(DynamicHub.java:2271)
	at io.grpc.netty.shaded.io.netty.channel.ReflectiveChannelFactory.<init>(ReflectiveChannelFactory.java:34)
	... 22 common frames omitted
```

### How to Reproduce?

Run the tutorial on gRPC mock and then launch a test on the mock themselves using `http://localhost:9090` as the target endpoint.

### Microcks version or git rev

nightly - 1.9.x

### Additional information

Only for the Uber native distribution.

**Comment by lbroudoux** [comment]
Got a new exception stack trace this morning when testing the fresh `nightly-native`: 

```
08:24:28.649 ERROR 1 --- [    task-6] i.g.m.service.TestRunnerService          : Throwable while testing operation getPets

io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
	at io.github.microcks.util.grpc.GrpcTestRunner.runTest(GrpcTestRunner.java:195)
	at io.github.microcks.util.grpc.GrpcTestRunner.runTest(GrpcTestRunner.java:61)
	at io.github.microcks.service.TestRunnerService.launchTestsInternal(TestRunnerService.java:211)
	at java.base@17.0.10/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
	at org.springframework.util.concurrent.FutureUtils.lambda$toSupplier$0(FutureUtils.java:74)
	at java.base@17.0.10/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:838)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
Caused by: io.grpc.netty.shaded.io.netty.channel.ChannelException: Unable to create Channel from class class io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel
	at io.grpc.netty.shaded.io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:46)
	at io.grpc.netty.shaded.io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:310)
	at io.grpc.netty.shaded.io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:227)
	at io.grpc.netty.shaded.io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:265)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:34)
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:259)
	at io.grpc.internal.InternalSubchannel.access$400(InternalSubchannel.java:66)
	at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:201)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126)
	at io.grpc.internal.ManagedChannelImpl$NameResolverListener.onResult(ManagedChannelImpl.java:1886)
	at io.grpc.internal.RetryingNameResolver$RetryingListener.onResult(RetryingNameResolver.java:98)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:333)
	... 5 common frames omitted
Caused by: org.graalvm.nativeimage.MissingReflectionRegistrationError: The program tried to reflectively invoke method public io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel() without it being registered for runtime reflection. Add it to the reflection metadata to solve this problem. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#reflection for help.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.MissingReflectionRegistrationUtils.forQueriedOnlyExecutable(MissingReflectionRegistrationUtils.java:97)
	at java.base@17.0.10/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:74)
	at java.base@17.0.10/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:496)
	at java.base@17.0.10/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at io.grpc.netty.shaded.io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:44)
	... 18 common frames omitted
```
