### ISSUE TITLE
The docker-compose installation do not work with the last version of microcks

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks#146]
When installing microcks as explained here:
http://microcks.github.io/installing/docker-compose/

The containers start successfully:

```sh
$ docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS                                        NAMES
8dd6a52e230b        microcks/microcks:latest                   "/deployments/run-ja…"   19 seconds ago      Up 17 seconds       8778/tcp, 0.0.0.0:8080->8080/tcp, 9779/tcp   microcks
f2110fe3d911        microcks/microcks-postman-runtime:latest   "node app.js"            20 seconds ago      Up 19 seconds       3000/tcp                                     microcks-postman-runtime
c823472e969a        jboss/keycloak:3.4.0.Final                 "/opt/jboss/docker-e…"   20 seconds ago      Up 19 seconds       0.0.0.0:8180->8080/tcp                       microcks-keycloak
b9fcb53c5f05        mongo:3.3.12                               "/entrypoint.sh mong…"   20 seconds ago      Up 19 seconds       27017/tcp                                    microcks-mongo
```

I can login with the default admin account but I cannot do anything with the UI. 

There are a lot of errors in the js console:
<img width="1418" alt="Screen Shot 2019-05-07 at 11 15 25" src="https://user-images.githubusercontent.com/7472564/57311359-7ffc1b80-70b9-11e9-98cc-8b5a6367db56.png">

As well as in the microcks container logs:

```sh
$ docker logs microcks
[ERROR] org.keycloak.adapters.rotation.JWKPublicKeyLocator - Error when sending request to retrieve realm keys
org.keycloak.adapters.HttpClientAdapterException: IO error
	at org.keycloak.adapters.HttpAdapterUtils.sendJsonHttpRequest(HttpAdapterUtils.java:58)
	at org.keycloak.adapters.rotation.JWKPublicKeyLocator.sendRequest(JWKPublicKeyLocator.java:99)
	at org.keycloak.adapters.rotation.JWKPublicKeyLocator.getPublicKey(JWKPublicKeyLocator.java:63)
	at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.getPublicKey(AdapterRSATokenVerifier.java:44)
	at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:55)
	at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:37)
	at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken(BearerTokenRequestAuthenticator.java:87)
	at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate(BearerTokenRequestAuthenticator.java:82)
	at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:68)
	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.authenticateInternal(AbstractKeycloakAuthenticatorValve.java:203)
	at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.authenticate(KeycloakAuthenticatorValve.java:50)
	at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.doAuthenticate(KeycloakAuthenticatorValve.java:57)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:575)
	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:120)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.keycloak.adapters.HttpAdapterUtils.sendJsonHttpRequest(HttpAdapterUtils.java:37)
	... 26 common frames omitted
[ERROR] org.keycloak.adapters.rotation.AdapterRSATokenVerifier - Didn't find publicKey for kid: JLsO7ZD9QPF5_s23ZqhnIOb0R7RebnOEeVLOX9M_1EU
[ERROR] org.keycloak.adapters.rotation.AdapterRSATokenVerifier - Didn't find publicKey for kid: JLsO7ZD9QPF5_s23ZqhnIOb0R7RebnOEeVLOX9M_1EU
[ERROR] org.keycloak.adapters.BearerTokenRequestAuthenticator - Failed to verify token
```

The error seems to be that the keycloak URL is set to http://localhost:8180/auth, which only works from the host but not from within the container.

And I cannot find a single URL that would be valid from within the microcks container and from the host. Any idea ?

**Comment by francesco-peleggi** [comment]
similar problem, I'm on a vm with fedora workstation (latest), after running the docker compose the keycloak and mongo containers just stop working

**Comment by sercastiGL** [comment]
The container needs to be able to reach the keycloak server with the public URL.
When you configure the KEYCLOAK_AUTH_URL value during the installation, it has to be an internet address both available to your browser for redirection, and internally for inter-containers communication. See #119 for more info. 

I fixed it in my case switching from CentOS to Ubuntu, where firewalld is not an issue.
See this for more info: https://github.com/moby/moby/issues/32138

**Comment by lbroudoux** [comment]
Documentation at https://microcks.github.io/documentation/installing/docker-compose/ was updated to emphasize the `docker.for.mac.localhost` or `docker.for.win.localhost`values. On Linux, you'll to play around with firewall but that is really dependent on your distro. See comments from here: https://github.com/moby/moby/issues/32138#issuecomment-403314792 for CentOS/RHEL based distros.
