### ISSUE TITLE
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /microcks-keycloak-config/microcks-realm-sample.json (No such file or directory)

### ISSUE THREAD

**Issue by alexespejo** [microcks/microcks#188]
**Error se produce al iniciar el contenedor desde docker-compose**

22:14:09,763 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 51) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./auth: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:84)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
        at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:162)
        at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2298)
        at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:340)
        at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:253)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:120)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
        at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
        at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:250)
        at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:133)
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:565)
        at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:536)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:578)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
        ... 6 more
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /microcks-keycloak-config/microcks-realm-sample.json (No such file or directory)
        at org.keycloak.services.resources.KeycloakApplication.importRealms(KeycloakApplication.java:368)
        at org.keycloak.services.resources.KeycloakApplication.migrateAndBootstrap(KeycloakApplication.java:231)
        at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:144)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:227)
        at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:135)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
        ... 28 more
Caused by: java.io.FileNotFoundException: /microcks-keycloak-config/microcks-realm-sample.json (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.keycloak.services.resources.KeycloakApplication.importRealms(KeycloakApplication.java:366)
        ... 37 more

22:14:09,771 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("deployment" => "keycloak-server.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./auth" => "java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
    Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
    Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /microcks-keycloak-config/microcks-realm-sample.json (No such file or directory)
    Caused by: java.io.FileNotFoundException: /microcks-keycloak-config/microcks-realm-sample.json (No such file or directory)"}}

**Comment by alexespejo** [comment]
**docker-compose:**
version: '3.7'
networks:
  main:
services:
  mongo:
    image: mongo:3.3.12
    container_name: microcks-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      main:
        aliases:
          - mongo
  postman:
    image: microcks/microcks-postman-runtime:latest
    container_name: microcks-postman-runtime
    networks:
      main:
        aliases:
          - postman
  keycloak:
    image: jboss/keycloak:3.4.0.Final
    command: "-b 0.0.0.0 -Dkeycloak.import=/microcks-keycloak-config/microcks-realm-sample.json"
    container_name: microcks-keycloak
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak-realm:/microcks-keycloak-config
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "123"
    networks:
      main:
        aliases:
          - keycloak
  app:
    depends_on:
      - mongo
      - postman
      - keycloak
    image: microcks/microcks:latest
    container_name: microcks
    volumes:
      - ./config:/deployments/config
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=microcks
      - POSTMAN_RUNNER_URL=http://postman:3000
      - TEST_CALLBACK_URL=http://microcks:8080
      #- KEYCLOAK_URL=http://localhost:8180/auth
      - SERVICES_UPDATE_INTERVAL=0 0 0/2 * * *
      #- KEYCLOAK_URL=http://docker.for.mac.localhost:8180/auth
      - KEYCLOAK_URL=http://docker.for.win.localhost:8180/auth
    networks:
      main:
        aliases:
          - microcks
volumes:
  mongo-data:

**Comment by lbroudoux** [comment]
Hi,
seems like the `./keycloak-realm` folder is not mounted as volume into the keycloak container. Is it present on your file system ? Do you launch docker-compose from the `./install/docker-compose` directory ?
Cheers

**Comment by lbroudoux** [comment]
Close due to inactivity. Please comment to re-open the issue if needed.
