### ISSUE TITLE
org.keycloak.adapters.rotation.AdapterRSATokenVerifier - Didn't find publicKey for kid

### ISSUE THREAD

**Issue by alexespejo** [microcks/microcks#204]
[DEBUG] io.github.microcks.web.SecretController - Counting secrets...
[DEBUG] io.github.microcks.web.SecretController - Getting secrets list for page 0 and size 20
[DEBUG] io.github.microcks.web.ServiceController - Counting services by type...
[DEBUG] io.github.microcks.web.InvocationController - Getting invocations stats for last 20 days
[DEBUG] io.github.microcks.web.InvocationController - Getting top 20 invocations stats for day 20200404
[ERROR] org.keycloak.adapters.rotation.AdapterRSATokenVerifier - Didn't find publicKey for kid: zBPVl_JMryWZAe7DCs_PmNc9QTFvMgCH-guYc3o0bFI
[ERROR] org.keycloak.adapters.rotation.AdapterRSATokenVerifier - Didn't find publicKey for kid: zBPVl_JMryWZAe7DCs_PmNc9QTFvMgCH-guYc3o0bFI
[ERROR] org.keycloak.adapters.BearerTokenRequestAuthenticator - Failed to verify token
org.keycloak.common.VerificationException: Didn't find publicKey for specified kid
        at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.getPublicKey(AdapterRSATokenVerifier.java:47)
        at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:55)
        at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:37)
        at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken(BearerTokenRequestAuthenticator.java:87)
        at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate(BearerTokenRequestAuthenticator.java:82)
        at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:68)
        at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.authenticateInternal(AbstractKeycloakAuthenticatorValve.java:203)
        at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.authenticate(KeycloakAuthenticatorValve.java:50)
        at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.doAuthenticate(KeycloakAuthenticatorValve.java:57)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:575)
        at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by lbroudoux** [comment]
Hi,
usually this kind of error occurs when there's a mix of HTTP and HTTPS setup in your config ; ie. you've first reach Keycloak using HTTPS and then the backend is trying to reach Keycloak using HTTP.

Could you detail your installation method and setup ?

**Comment by alexespejo** [comment]
Hello,
The installation I am doing in windows 10.

Modify the docker-compese version to 3.7 so that the MongoDB container can work.

Updated microcks.yml is attached.

version: '3.7'
networks:
  main:
services:
  mongo:
    image: mongo:3.4.23
    container_name: microcks-mongo
    volumes:
      - microcks-data:/data/db
    networks:
      main:
        aliases:
          - mongo
  postman:
    image: microcks/microcks-postman-runtime:latest
    container_name: microcks-postman-runtime
    networks:
      main:
        aliases:
          - postman
  keycloak:
    image: jboss/keycloak:9.0.2
    command: "-b 0.0.0.0 -Dkeycloak.import=/microcks-keycloak-config/microcks-realm-sample.json"
    container_name: microcks-keycloak
    ports:
      - "8180:8080"
      - "8543:8443"
    volumes:
      - ./keycloak-realm:/microcks-keycloak-config
      - ./keystore:/etc/x509/https
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "123"
    networks:
      main:
        aliases:
          - keycloak
  app:
    depends_on:
      - mongo
      - postman
      - keycloak
    image: microcks/microcks:latest
    container_name: microcks
    volumes:
      - ./config:/deployments/config
      - ./keystore:/deployments/keystore
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=microcks
      - POSTMAN_RUNNER_URL=http://postman:3000
      - TEST_CALLBACK_URL=http://microcks:8080
      #- KEYCLOAK_URL=https://localhost:8543/auth
      - SERVICES_UPDATE_INTERVAL=0 0 0/2 * * *
      #- KEYCLOAK_URL=https://docker.for.mac.localhost:8543/auth
      - KEYCLOAK_URL=https://docker.for.win.localhost:8543/auth
    networks:
      main:
        aliases:
          - microcks
volumes:
  microcks-data:

**Comment by lbroudoux** [comment]
Ok thanks. 
A few things to check:
- Is https://docker.for.win.localhost:8543/auth reachable and leads to Keycloak ? From your local host ? From the Microcks container ?
- Is Keycloak realm configured to redirect to https://localhost:8080 ?
- Is the configuration on the Microcks side correct when calling https://localhost:8080/api/keycloak ? Is the keycloak url correct ?
- Is the login flow working ?

**Comment by alexespejo** [comment]
Hello,
My answers

- Is https://docker.for.win.localhost:8543/auth reachable and leads to Keycloak ? From your local host ? From the Microcks container ?
**YES**
- Is Keycloak realm configured to redirect to https://localhost:8080 ?
**YES**
- Is the configuration on the Microcks side correct when calling https://localhost:8080/api/keycloak ? Is the keycloak url correct ?
**There was an unexpected error (type=Not Found, status=404). No message available**
- Is the login flow working ?
**YES**

![localhost 8080](https://user-images.githubusercontent.com/3868292/79502430-37512000-7ff5-11ea-8271-b76d2b85a243.png)
![docker for win localhost 8543](https://user-images.githubusercontent.com/3868292/79502426-361ff300-7ff5-11ea-9668-8976e139dbd9.png)
![localhost 8080 api keycloak](https://user-images.githubusercontent.com/3868292/79502429-37512000-7ff5-11ea-8437-a5458adacde8.png)

**Comment by alexespejo** [comment]
Hello,
Attached log.

[log_microcks.txt](https://github.com/microcks/microcks/files/4489733/log_microcks.txt)

**Comment by lbroudoux** [comment]
Hi,

Can you please try to add the following property :

`keycloak.disable-trust-manager=true`

to the config/application.properties file within the docket-compose folder ?

For some reason the Keycloak certificate cannot be fully trusted it seems ...

**Comment by alexespejo** [comment]
**Dear**,
Adding the property keycloak.disable-trust-manager = true was solved.
Now it works perfectly.

Thanks for the support.

![microcks](https://user-images.githubusercontent.com/3868292/79595156-f6fcab00-80a3-11ea-93dc-3a1f6736ac12.png)

**Comment by lbroudoux** [comment]
Great ! Glad to know this. Happy mocking !
