### ISSUE TITLE
Fix OpenAPI importer that does not support operation with only Query parameters

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#49]
OpenAPI importer crashes when importing API Operation definition that just contain query parameters and no path parameters. You may encounter these type of exceptions stack traces:

```
java.lang.NullPointerException: null
        at io.github.microcks.util.DispatchCriteriaHelper.buildFromParamsMap(DispatchCriteriaHelper.java:263)
        at io.github.microcks.util.openapi.OpenAPIImporter.getMessageDefinitions(OpenAPIImporter.java:248)
        at io.github.microcks.service.ServiceService.importServiceDefinition(ServiceService.java:127)
        at io.github.microcks.task.ImportServiceDefinitionTask.importServiceDefinition(ImportServiceDefinitionTask.java:95)
```

Note that operation containing a mix of path and query parameters are ok.

**Comment by lbroudoux** [comment]
Done
