### ISSUE TITLE
GRPC Server cannot be started - Input stream does not contain valid private key

### ISSUE THREAD

**Issue by jennerEVRFLL** [microcks/microcks#492]
Hello, 

I´ve been struggling to properly install Microcks on k8s v1.19.13. I´ve  deployed microcks on our company cluster and a local minikube instance (with no value changes & self generated certificates) via Helm Chart. 

```
Release "microcks" has been upgraded. Happy Helming!
NAME: microcks
LAST DEPLOYED: Wed Sep 22 14:33:03 2021
NAMESPACE: microcks
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing microcks.

Your release is named microcks.

To learn more about the release, try:

  $ helm status microcks
  $ helm get microcks

Microcks is available at https://microcks.ourDomain.com

GRPC mock service is available at "microcks-grpc.ourDomain.com".
It has been exposed using TLS passthrough on the Ingress controller, you should extract the certificate for your client using:

  $ kubectl get secret microcks-microcks-grpc-secret -n  -o jsonpath='{.data.tls\.crt}' | base64 -d > tls.crt

Keycloak has been deployed on https://keycloak.ourDomain.com/auth to protect user access.
You may want to configure an Identity Provider or add some users for your Microcks installation by login in using the
username and password found into 'microcks-keycloak-admin' secret."
```
Unfortunately if i look up the pod logs i get the following error:
<details>
<summary>Errorlog </summary> 

```
12:33:08.324 [INFO] io.github.microcks.MicrocksApplication - Starting MicrocksApplication using Java 11.0.12 on microcks-7f5b69f84-g8gzr with PID 1 (/deployments/app.jar started by ? in /deployments)
12:33:08.326 [DEBUG] io.github.microcks.MicrocksApplication - Running with Spring Boot v2.4.5, Spring v5.3.6
12:33:08.326 [INFO] io.github.microcks.MicrocksApplication - The following profiles are active: prod
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (jar:file:/deployments/app.jar!/BOOT-INF/lib/groovy-all-2.4.17.jar!/) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
12:33:12.830 [INFO] io.github.microcks.config.WebConfiguration - Starting web application configuration, using profiles: [prod]
12:33:12.832 [INFO] io.github.microcks.config.WebConfiguration - Web application fully configured
12:33:13.038 [INFO] org.mongodb.driver.cluster - Cluster created with settings {hosts=[microcks-mongodb:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
12:33:13.168 [INFO] org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:37582}] to microcks-mongodb:27017
12:33:13.169 [INFO] org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=microcks-mongodb:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=null, roundTripTimeNanos=33729577}
12:33:13.175 [INFO] org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:37581}] to microcks-mongodb:27017
12:33:13.226 [WARN] org.springframework.data.convert.CustomConversions - Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
12:33:13.281 [WARN] org.springframework.data.convert.CustomConversions - Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
12:33:14.338 [ERROR] io.github.microcks.util.grpc.GrpcServerStarter - GRPC Server cannot be started
java.lang.IllegalArgumentException: Input stream does not contain valid private key.
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:376)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:121)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forServer(GrpcSslContexts.java:137)
	at io.grpc.netty.shaded.io.grpc.netty.ProtocolNegotiators.from(ProtocolNegotiators.java:212)
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerProvider.newServerBuilderForPort(NettyServerProvider.java:45)
	at io.grpc.ServerRegistry.newServerBuilderForPort(ServerRegistry.java:133)
	at io.grpc.Grpc.newServerBuilderForPort(Grpc.java:136)
	at io.github.microcks.util.grpc.GrpcServerStarter.startGrpcServer(GrpcServerStarter.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:774)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
	at io.github.microcks.MicrocksApplication.main(MicrocksApplication.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.security.spec.InvalidKeySpecException: Neither RSA, DSA nor EC worked
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1144)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1123)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:374)
	... 41 common frames omitted
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at jdk.crypto.ec/sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:169)
	at java.base/java.security.KeyFactory.generatePrivate(KeyFactory.java:390)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1142)
	... 43 common frames omitted
Caused by: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at java.base/sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:350)
	at java.base/sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:355)
	at jdk.crypto.ec/sun.security.ec.ECPrivateKeyImpl.<init>(ECPrivateKeyImpl.java:74)
	at jdk.crypto.ec/sun.security.ec.ECKeyFactory.implGeneratePrivate(ECKeyFactory.java:237)
	at jdk.crypto.ec/sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:165)
	... 45 common frames omitted
12:33:15.890 [INFO] io.github.microcks.MicrocksApplication - Started MicrocksApplication in 8.334 seconds (JVM running for 9.65)
```

</details>

**Comment by lbroudoux** [comment]
Hi @jennerEVRFLL !

Thanks for raising this issue and sorry for inconvenience... I succeed reproducing it. It appears that certificate generation functions in Helm, generates a private key that are different from the one generated with `openssl`. I think it should have changed with recent updates of Helm as I clearly remember having tested this one...

I'm investigation what are the fix options for this. Stay tuned please.

**Comment by lbroudoux** [comment]
Hey!

Just produced and tested a fix. Don't know why but the private key generated by [Helm function](https://helm.sh/docs/chart_template_guide/function_list/#genselfsignedcert) is recognized as a key pair by default security provider in JVM. The fix I've implemented is to use the Bouncycastle security provider to extract the real private key from this key pair and use it in a second try.

The fix should be available in `quay.io/microcksd/microcks:latest` container image in few minutes. Be sure to remove older version to test this one out. Let me know the results.

**Comment by jennerEVRFLL** [comment]
Hey !
GRPC-Server starts correct now ! Thanks for fix.
