### ISSUE TITLE
Util module tests fails on windows

### ISSUE THREAD

**Issue by jonaslagoni** [microcks/microcks#705]
In Windows the `testBuildTypeSchemaFromJson` test fails, because of the prettier string comparison where the actual schema uses `\r\n` instead of the expected `\n` as tab encoding.

Here is the stack-trace:

```
testBuildTypeSchemaFromJson(io.github.microcks.util.openapi.OpenAPISchemaBuilderTest)  Time elapsed: 0.005 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{[
  "type" : "object",
  "properties" : {
    "foo" : {
      "type" : "string"
    },
    "flag" : {
      "type" : "boolean"
    },
    "list" : {
      "type" : "array",
      "items" : {
        "type" : "number"
      }
    },
    "obj" : {
      "type" : "object",
      "properties" : {
        "fizz" : {
          "type" : "string"
        }
      }
    },
    "objList" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "number" : {
            "type" : "number"
          }
        }
      }
    }
  }]
}> but was:<{[
  "type" : "object",
  "properties" : {
    "foo" : {
      "type" : "string"
    },
    "flag" : {
      "type" : "boolean"
    },
    "list" : {
      "type" : "array",
      "items" : {
        "type" : "number"
      }
    },
    "obj" : {
      "type" : "object",
      "properties" : {
        "fizz" : {
          "type" : "string"
        }
      }
    },
    "objList" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "number" : {
            "type" : "number"
          }
        }
      }
    }
] }
}>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at io.github.microcks.util.openapi.OpenAPISchemaBuilderTest.testBuildTypeSchemaFromJson(OpenAPISchemaBuilderTest.java:89)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

```

**Comment by lbroudoux** [comment]
It's really weird no one ever build Microcks on Windows 😜

**Comment by lbroudoux** [comment]
PR #706 is now merged. Thanks Jonas!
