### ISSUE TITLE
While calling GRPC service, receiving error

### ISSUE THREAD

**Issue by vishalmgada** [microcks/microcks#745]
We have mocked sample GRPC service provided in the microcks documentation and receiving error.
io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - Exception in onDataRead()

`2023-02-01T05:58:42.865259702Z 05:58:42.865 [WARN] io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - Exception in onDataRead()
2023-02-01T05:58:42.865295702Z java.lang.NullPointerException: null
2023-02-01T05:58:42.865299702Z 	at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:506)
2023-02-01T05:58:42.865302202Z 	at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler.access$900(NettyServerHandler.java:106)
2023-02-01T05:58:42.865304402Z 	at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler$FrameListener.onDataRead(NettyServerHandler.java:840)
2023-02-01T05:58:42.865307602Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:307)
2023-02-01T05:58:42.865309802Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$PrefaceFrameListener.onDataRead(DefaultHttp2ConnectionDecoder.java:691)
2023-02-01T05:58:42.865312302Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
2023-02-01T05:58:42.865314502Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:415)
2023-02-01T05:58:42.865317002Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:250)
2023-02-01T05:58:42.865319202Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
2023-02-01T05:58:42.865321302Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
2023-02-01T05:58:42.865323402Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
2023-02-01T05:58:42.865325502Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
2023-02-01T05:58:42.865327702Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:242)
2023-02-01T05:58:42.865329802Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
2023-02-01T05:58:42.865331802Z 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
2023-02-01T05:58:42.865333902Z 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
2023-02-01T05:58:42.865336102Z 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
2023-02-01T05:58:42.865338102Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2023-02-01T05:58:42.865340202Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2023-02-01T05:58:42.865342302Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2023-02-01T05:58:42.865344802Z 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)
2023-02-01T05:58:42.865346902Z 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
2023-02-01T05:58:42.865358002Z 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
2023-02-01T05:58:42.865360002Z 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
2023-02-01T05:58:42.865362002Z 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
2023-02-01T05:58:42.865363902Z 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
2023-02-01T05:58:42.865365902Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2023-02-01T05:58:42.865367802Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2023-02-01T05:58:42.865369902Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2023-02-01T05:58:42.865371802Z 	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2023-02-01T05:58:42.865373603Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2023-02-01T05:58:42.865375403Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2023-02-01T05:58:42.865392203Z 	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2023-02-01T05:58:42.865412003Z 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
2023-02-01T05:58:42.865416103Z 	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
2023-02-01T05:58:42.865418903Z 	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
2023-02-01T05:58:42.865434503Z 	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
2023-02-01T05:58:42.865440103Z 	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-02-01T05:58:42.865442303Z 	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-02-01T05:58:42.865447203Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2023-02-01T05:58:42.865456603Z 05:58:42.865 [WARN] io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler - Stream Error
2023-02-01T05:58:42.865462203Z io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception$StreamException: 
2023-02-01T05:58:42.865464403Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:172)
2023-02-01T05:58:42.865466403Z 	at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler.newStreamException(NettyServerHandler.java:817)
2023-02-01T05:58:42.865468403Z 	at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:515)
2023-02-01T05:58:42.865470303Z 	at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler.access$900(NettyServerHandler.java:106)
2023-02-01T05:58:42.865472303Z 	at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler$FrameListener.onDataRead(NettyServerHandler.java:840)
2023-02-01T05:58:42.865475503Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:307)
2023-02-01T05:58:42.865477603Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$PrefaceFrameListener.onDataRead(DefaultHttp2ConnectionDecoder.java:691)
2023-02-01T05:58:42.865489103Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
2023-02-01T05:58:42.865491503Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:415)
2023-02-01T05:58:42.865493603Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:250)
2023-02-01T05:58:42.865495603Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
2023-02-01T05:58:42.865497503Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
2023-02-01T05:58:42.865499403Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
2023-02-01T05:58:42.865501503Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
2023-02-01T05:58:42.865503503Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:242)
2023-02-01T05:58:42.865505303Z 	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
2023-02-01T05:58:42.865507403Z 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
2023-02-01T05:58:42.865509403Z 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
2023-02-01T05:58:42.865511303Z 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
2023-02-01T05:58:42.865513303Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2023-02-01T05:58:42.865515303Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2023-02-01T05:58:42.865517403Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2023-02-01T05:58:42.865519503Z 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)
2023-02-01T05:58:42.865521403Z 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
2023-02-01T05:58:42.865523403Z 	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
2023-02-01T05:58:42.865525403Z 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
2023-02-01T05:58:42.865527403Z 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
2023-02-01T05:58:42.865529403Z 	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
2023-02-01T05:58:42.865531203Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2023-02-01T05:58:42.865533103Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2023-02-01T05:58:42.865535003Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
2023-02-01T05:58:42.865537103Z 	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2023-02-01T05:58:42.865548903Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
2023-02-01T05:58:42.865554403Z 	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
2023-02-01T05:58:42.865556503Z 	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2023-02-01T05:58:42.865558403Z 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
2023-02-01T05:58:42.865560403Z 	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
2023-02-01T05:58:42.865562303Z 	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
2023-02-01T05:58:42.865564203Z 	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
2023-02-01T05:58:42.865566303Z 	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-02-01T05:58:42.865568103Z 	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-02-01T05:58:42.865570103Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2023-02-01T05:58:42.865572403Z Caused by: java.lang.NullPointerException: null
2023-02-01T05:58:42.865574803Z 	at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:506)
2023-02-01T05:58:42.865577003Z 	... 39 common frames omitted`

**Comment by lbroudoux** [comment]
Hi,

Could you please add more details here:
* What version of Microcks?
* What samples you're actually loading?
* What request you're actually issuing to the server?
* What client you're using?
* etc..

Thanks,

**Comment by vishalmgada** [comment]
@lbroudoux 

I tried to mock the GRPC example provided by microcks, below are the link

- proto file - https://raw.githubusercontent.com/microcks/microcks/master/samples/hello-v1.proto
- postman collection - https://raw.githubusercontent.com/microcks/microcks/master/samples/HelloService.postman.json

When I was calling this mock service from postman, we observed the request was not reaching the pod. Then we added "nginx.ingress.kubernetes.io/backend-protocol: "GRPCS" to the helm and now we see request is coming to the pod but with above error.

Microcks Version - 1.6.1

**Comment by vishalmgada** [comment]
@lbroudoux  - Could you please help with above?

I am suspecting we have missed some configuration in the helm values due to which we are getting above issue. But, we are not able to identify the config missing.

**Comment by lbroudoux** [comment]
Hey! Sorry for the late reply.

The `GRPCS` value seems suspicious to me and not necessary as the Microcks Helm chart and operator already put the `nginx.ingress.kubernetes.io/backend-protocol: "GRPC"` and `nginx.ingress.kubernetes.io/ssl-passthrough: "true"` annotations.

I've succeeded in validating it behind an Nginx ingress controller and I know some other people succeed behind other controllers. That's why we added the option of providing your own `.Values.microcks.grpcIngressAnnotations` in case you were running a customer ingress controller + class.

Could you provide details on the deployment environment? Kube distribution? Ingress controller or node port or native load-balancer? Have you checked you didn't have any sidecar / node daemon set / anything that could alter input streaam?

**Comment by vishalmgada** [comment]
@lbroudoux - Thank you, we are checking on this and if we are unable to resolve it. I will share further details and values.

**Comment by mondeep-maity** [comment]
Hi @lbroudoux We have deployed the service in the AKS cluster, When we are doing port-forward to the pod or service its works but when we are hitting the ingress via postman it's throwing the below error.

```
Internal error
Operation couldn’t be completed because of an internal error at the server.
Received RST_STREAM with code 0
```

We are using the below annotations. Do we have to use "appProtocol: grpc" in service as well?
```
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"

```

**Comment by lbroudoux** [comment]
I think that appProtocol is not necessary. However I think you absolutely need to have the ssl-passthrough annotation.

**Comment by mondeep-maity** [comment]
> I think that appProtocol is not necessary. However I think you absolutely need to have the ssl-passthrough annotation.

I am already using **SSL-passthrough** notification. I checked the ingress log too and see the below. Please let me know if any ideas on this error.
`1158#1158: *893500 upstream prematurely closed connection while reading response header from upstream`

**Comment by mondeep-maity** [comment]
This issue can be closed, We have fixed the issue @lbroudoux.

**Comment by vishalmgada** [comment]
It was a configuration issue at our end. Redeploying it has helped. Hence closing the issue.
