### ISSUE TITLE
[GraphQL] Incorrect operation name resolution when there are multiple operations with the same prefix

### ISSUE THREAD

**Issue by gudeteira** [microcks/microcks#763]
Hello,
While testing Microcks with GraphQL, i discovered that if an API has two operations starting with the same name for the same method, the operation resolution is not correct

Starting from the following example:
```
# microcksId: Movie Graph API : 1.0
schema {
  query: Query
  mutation: Mutation
}
type Film {
  id: String!
  title: String!
  episodeID: Int!
  director: String!
  starCount: Int!
  rating: Float!
}

type FilmsConnection {
  totalCount: Int!
  films: [Film]
}

input Review {
  comment: String
  rating: Int
}

type Query {
  films: FilmsConnection
  film(id: String): Film
}

type Mutation {
  addStar(filmId: String): Film
  addReview(filmId: String, review: Review): Film
}
```
When making the following curl request I get an error
```
curl --location --request POST 'http://localhost:8080/graphql/Movie+Graph+API/1.0' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"query film ($id: String) {\n    film (id: $id) {\n        id\n        title\n        episodeID\n        director\n        starCount\n        rating\n    }\n}","variables":{"id":"ZmlsbXM6MQ=="}}'

{"timestamp":1678174708022,"status":500,"error":"Internal Server Error","path":"/graphql/Movie+Graph+API/1.0"}
```

Operation "**films**" is being executed instead of "**film**"
```
07:38:28.019 DEBUG 1 --- [80-exec-10] i.g.microcks.web.GraphQLController       : Processing a 'QUERY' operation with name 'film'
07:38:28.019 DEBUG 1 --- [80-exec-10] i.g.microcks.web.GraphQLController       : Found a valid operation films with rules: null
07:38:28.019 DEBUG 1 --- [80-exec-10] i.g.microcks.web.GraphQLController       : Dispatch criteria for finding response is null
```

```
07:38:28.015  INFO 1 --- [80-exec-10] i.g.microcks.web.GraphQLController       : Servicing GraphQL mock response for service [Movie+Graph+API, 1.0]
07:38:28.015 DEBUG 1 --- [80-exec-10] i.g.microcks.web.GraphQLController       : Request body: {"query":"query film ($id: String) {\n    film (id: $id) {\n        id\n        title\n        episodeID\n        director\n        starCount\n        rating\n    }\n}","variables":{"id":"ZmlsbXM6MQ=="}}
07:38:28.019 DEBUG 1 --- [80-exec-10] i.g.microcks.web.GraphQLController       : Got this graphqlOperation: OperationDefinition{name='film', operation=QUERY, variableDefinitions=[VariableDefinition{name='id', type=TypeName{name='String'}, defaultValue=null, directives=[]}], directives=[], selectionSet=SelectionSet{selections=[Field{name='film', alias='null', arguments=[Argument{name='id', value=VariableReference{name='id'}}], directives=[], selectionSet=SelectionSet{selections=[Field{name='id', alias='null', arguments=[], directives=[], selectionSet=null}, Field{name='title', alias='null', arguments=[], directives=[], selectionSet=null}, Field{name='episodeID', alias='null', arguments=[], directives=[], selectionSet=null}, Field{name='director', alias='null', arguments=[], directives=[], selectionSet=null}, Field{name='starCount', alias='null', arguments=[], directives=[], selectionSet=null}, Field{name='rating', alias='null', arguments=[], directives=[], selectionSet=null}]}}]}}
07:38:28.019 DEBUG 1 --- [80-exec-10] i.g.microcks.web.GraphQLController       : Processing a 'QUERY' operation with name 'film'
07:38:28.019 DEBUG 1 --- [80-exec-10] i.g.microcks.web.GraphQLController       : Found a valid operation films with rules: null
07:38:28.019 DEBUG 1 --- [80-exec-10] i.g.microcks.web.GraphQLController       : Dispatch criteria for finding response is null
07:38:28.021 ERROR 1 --- [80-exec-10] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at io.github.microcks.web.GraphQLController.filterFieldSelection(GraphQLController.java:456)
	at io.github.microcks.web.GraphQLController.processGraphQLQuery(GraphQLController.java:368)
	at io.github.microcks.web.GraphQLController.execute(GraphQLController.java:182)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[...]
```

**Comment by lbroudoux** [comment]
Fix is now available in new `quay.io/microcks/microcks:next` image and will be propagated in `1.7.0` release to come.
