### ISSUE TITLE
GooglePubSub: Cannot invoke "java.util.Map.keySet()" because "m" is null

### ISSUE THREAD

**Issue by olissao** [microcks/microcks#899]
### Describe the bug

Getting an Error with ASYNC API using Google pub/Sub. when I run docker compose -f docker-compose.yml -f docker-compose-async-addon.yml up -d I got INFO [io.git.mic.min.asy.pro.GooglePubSubProducerManager] (QuarkusQuartzScheduler_Worker-23) Publishing on topic {PubSubPaymentService-1.0.0-payment-topic}, message: {"eventType":"PAYMENT_EVENT","clientId":"2e4a8243-aa87-43c7-a37a-26a172f62ca0","email":"[user@example.com](mailto:user@example.com)","enabled":true,"createdAt":"2019-08-24T14:15:22Z","dueDate":"2019-10-24T14:15:22Z"}
2023-08-29 11:51:59 2023-08-29 15:51:59,965 ERROR [org.qua.cor.JobRunShell] (QuarkusQuartzScheduler_Worker-23) Job DEFAULT.6da64b5bd2ee-d7516b3c-6c82-4fcc-a83a-137f78609bbc threw an unhandled Exception: : java.lang.NullPointerException: Cannot invoke "java.util.Map.keySet()" because "m" is null
2023-08-29 11:51:59 at com.google.protobuf.MapField$MutatabilityAwareMap.putAll(MapField.java:337)
2023-08-29 11:51:59 at com.google.pubsub.v1.PubsubMessage$Builder.putAllAttributes(PubsubMessage.java:1123)
2023-08-29 11:51:59 at io.github.microcks.minion.async.producer.GooglePubSubProducerManager.publishMessage(GooglePubSubProducerManager.java:139)
2023-08-29 11:51:59 at io.github.microcks.minion.async.producer.GooglePubSubProducerManager_ClientProxy.publishMessage(Unknown Source)
2023-08-29 11:51:59 at io.github.microcks.minion.async.producer.ProducerManager.produceAsyncMockMessagesAt(ProducerManager.java:181)
2023-08-29 11:51:59 at io.github.microcks.minion.async.producer.ProducerManager_ClientProxy.produceAsyncMockMessagesAt(Unknown Source)
2023-08-29 11:51:59 at io.github.microcks.minion.async.ProducerScheduler$AsyncMockProducerJob.execute(ProducerScheduler.java:95)
2023-08-29 11:51:59 at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
2023-08-29 11:51:59 at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2023-08-29 11:51:59
2023-08-29 11:51:59 2023-08-29 15:51:59,965 ERROR [org.qua.cor.ErrorLogger] (QuarkusQuartzScheduler_Worker-23) Job (DEFAULT.6da64b5bd2ee-d7516b3c-6c82-4fcc-a83a-137f78609bbc threw an exception.: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException: Cannot invoke "java.util.Map.keySet()" because "m" is null]
2023-08-29 11:51:59 at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
2023-08-29 11:51:59 at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2023-08-29 11:51:59 Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.keySet()" because "m" is null
2023-08-29 11:51:59 at com.google.protobuf.MapField$MutatabilityAwareMap.putAll(MapField.java:337)
2023-08-29 11:51:59 at com.google.pubsub.v1.PubsubMessage$Builder.putAllAttributes(PubsubMessage.java:1123)
2023-08-29 11:51:59 at io.github.microcks.minion.async.producer.GooglePubSubProducerManager.publishMessage(GooglePubSubProducerManager.java:139)
2023-08-29 11:51:59 at io.github.microcks.minion.async.producer.GooglePubSubProducerManager_ClientProxy.publishMessage(Unknown Source)
2023-08-29 11:51:59 at io.github.microcks.minion.async.producer.ProducerManager.produceAsyncMockMessagesAt(ProducerManager.java:181)
2023-08-29 11:51:59 at io.github.microcks.minion.async.producer.ProducerManager_ClientProxy.produceAsyncMockMessagesAt(Unknown Source)
2023-08-29 11:51:59 at io.github.microcks.minion.async.ProducerScheduler$AsyncMockProducerJob.execute(ProducerScheduler.java:95)
2023-08-29 11:51:59 at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
2023-08-29 11:51:59 ... 1 more
2023-08-29 11:51:59
2023-08-29 11:52:02 2023-08-29 15:52:02,964 INFO [io.git.mic.min.asy.pro.ProducerManager] (QuarkusQuartzScheduler_Worker-21) Producing async mock messages for frequency: 3
2023-08-29 11:52:02 2023-08-29 15:52:02,964 INFO [io.git.mic.min.asy.pro.GooglePubSubProducerManager] (QuarkusQuartzScheduler_Worker-21) Publishing on topic {PubSubPaymentService-1.0.0-payment-topic}, message: {"eventType":"PAYMENT_EVENT","clientId":"2e4a8243-aa87-43c7-a37a-26a172f62ca0","email":"[user@example.com](mailto:user@example.com)","enabled":true,"createdAt":"2019-08-24T14:15:22Z","Date":"2019-10-24T14:15:22Z"}
2023-08-29 11:52:02 2023-08-29 15:52:02,965 ERROR [org.qua.cor.JobRunShell] (QuarkusQuartzScheduler_Worker-21) Job DEFAULT.6da64b5bd2ee-d7516b3c-6c82-4fcc-a83a-137f78609bbc threw an unhandled Exception: : java.lang.NullPointerException: Cannot invoke "java.util.Map.keySet()" because "m" is null
2023-08-29 11:52:02 at com.google.protobuf.MapField$MutatabilityAwareMap.putAll(MapField.java:337)
2023-08-29 11:52:02 at com.google.pubsub.v1.PubsubMessage$Builder.putAllAttributes(PubsubMessage.java:1123)
2023-08-29 11:52:02 at io.github.microcks.minion.async.producer.GooglePubSubProducerManager.publishMessage(GooglePubSubProducerManager.java:139)
2023-08-29 11:52:02 at io.github.microcks.minion.async.producer.GooglePubSubProducerManager_ClientProxy.publishMessage(Unknown Source)
2023-08-29 11:52:02 at io.github.microcks.minion.async.producer.ProducerManager.produceAsyncMockMessagesAt(ProducerManager.java:181)
2023-08-29 11:52:02 at io.github.microcks.minion.async.producer.ProducerManager_ClientProxy.produceAsyncMockMessagesAt(Unknown Source)
2023-08-29 11:52:02 at io.github.microcks.minion.async.ProducerScheduler$AsyncMockProducerJob.execute(ProducerScheduler.java:95)
2023-08-29 11:52:02 at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
2023-08-29 11:52:02 at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2023-08-29 11:52:02
2023-08-29 11:52:02 2023-08-29 15:52:02,965 ERROR [org.qua.cor.ErrorLogger] (QuarkusQuartzScheduler_Worker-21) Job (DEFAULT.6da64b5bd2ee-d7516b3c-6c82-4fcc-a83a-137f78609bbc threw an exception.: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException: Cannot invoke "java.util.Map.keySet()" because "m" is null]
2023-08-29 11:52:02 at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
2023-08-29 11:52:02 at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2023-08-29 11:52:02 Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.keySet()" because "m" is null

### Microcks version or git rev

latest

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

**Comment by lbroudoux** [comment]
This comes from discussion #898. It appears that publishing to PubSub fails when there are no headers for the message.
