### ISSUE TITLE
mock graphql API got error message "service" is null

### ISSUE THREAD

**Issue by Marcotsept** [microcks/microcks#900]
### Describe the bug

Hi, I would need to help. I'm following this page `https://microcks.io/documentation/using/graphql/` to mock graphql API, when I call the API on postman I got this error.

```
java.lang.NullPointerException: Cannot invoke "io.github.microcks.domain.Service.getOperations()" because "service" is null
microcks                  | 	at io.github.microcks.web.RestController.execute(RestController.java:130)
microcks                  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
microcks                  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
microcks                  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
microcks                  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
microcks                  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
microcks                  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
microcks                  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
microcks                  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
microcks                  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
microcks                  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
microcks                  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)
microcks                  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)
microcks                  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
microcks                  | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
microcks                  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:696)
microcks                  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
microcks                  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
microcks                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
microcks                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
microcks                  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
microcks                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
microcks                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
microcks                  | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
microcks                  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
microcks                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
microcks                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
microcks                  | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
microcks                  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
microcks                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
microcks                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
microcks                  | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
microcks                  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
microcks                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
microcks                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
microcks                  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
microcks                  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
microcks                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
microcks                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
microcks                  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
microcks                  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
microcks                  | 	at org.keycloak.adapters.tomcat.AbstractAuthenticatedActionsValve.invoke(AbstractAuthenticatedActionsValve.java:67)
microcks                  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
microcks                  | 	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181)
microcks                  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
microcks                  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
microcks                  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
microcks                  | 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
microcks                  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
microcks                  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
microcks                  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
microcks                  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
microcks                  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
microcks                  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
microcks                  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
microcks                  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
microcks                  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
microcks                  | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

import schema file and import collection json file, then calling API on postman with Graphql body params

### Microcks version or git rev

1.7.1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

### Additional information

My PC: M1 chips

I found that one page `https://microcks.io/blog/graphql-features-what-to-expect/`, the URL is `http://localhost:8080/graphql/Movie+Graph.....` but my URL is `http://localhost:8080/rest/Movie+Graph+API/1.0film`, I don't know it is a problem or not.  
![Screenshot 2023-08-31 at 12 17 49 AM](https://github.com/microcks/microcks/assets/17099973/7fa2f58f-3523-46fd-ac95-b7af02946179)

**Comment by Marcotsept** [comment]
It works by created new collection json myself.

**Comment by lbroudoux** [comment]
Thanks for the follow-up! Do you mean there's a problem with official documentation or samples? The URL of mocks coming from the sample `films.graphql` must actually be `http://localhost:8080/graphql/Movie+Graph+API/1.0`. Maybe you got a `rest` endpoint because you didn't check the `secondary artifact` box when importing the Postman collection? In that case, it overrides the service type definition...
Let me know if we can make things clearer in the documentation.
