### ISSUE TITLE
microcks uber and microcks standard produce different schema conformance outcomes and uber breaks with  non success cases

### ISSUE THREAD

**Issue by cloudbackenddev** [microcks/microcks#904]
### Describe the bug

I have a open api spec that was tested successfully with standard microcks for schema conformance (refer below)  (url)
[openapi-spec.yaml.txt](https://github.com/microcks/microcks/files/12505944/openapi-spec.yaml.txt)

The same schema i tried to validate with testcontainers (quay.io/microcks/microcks-uber:nightly). I see two primary issues.

**Problem1**
Spring boot responds with  "application/problem+json"  for any errors. In standard microcks  this passes even if content-type is set as "application/json". In uber distribution this fails. 

**Problem2**
   If i change the content-type for all error response codes in api spec (from application/problem+json to application/json ) then the above error is gone but get a broken pipe error. Something breaks connection between microcks and app. Based on my observation I see this occurs post the first response having response 400 with content-type set as "application/problem+json"

Can you please check and advise on this as negative scenarios are also need to be validated in contract tests?

Refer additional information for logs, Also attached the schema i tested

### Expected behavior

Microcks and Uber should produce same conformance output

### Actual behavior

They are  different. Uber breaks during conformance tests

### How to Reproduce?

Try with any spring boot 3 to 4 consecutive negative scenarios (for eg 400 response code) with content-type  set as application/problem+json

### Microcks version or git rev

quay.io/microcks/microcks-uber:nightly

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

### Additional information

**Logs for Problem1:**

"success" : false,
    "elapsedTime" : 164,
    "operationName" : "POST /api/users",
    "testStepResults" : [ {
      "success" : false,
      "elapsedTime" : 146,
      "requestName" : "duplicate-user",
      "message" : "Response Content-Type does not match expected one. Expecting application/json but got application/problem+json\n"
    }, {
      "success" : false,
      "elapsedTime" : 14,
      "requestName" : "invalid-email",
      "message" : "Response Content-Type does not match expected one. Expecting application/json but got application/problem+json\n"
    },

**Test Result Logs for Problem2**

 "success" : false,
    "elapsedTime" : 287,
    "operationName" : "POST /api/users",
    "testStepResults" : [ {
      "success" : true,
      "elapsedTime" : 203,
      "requestName" : "user-creation-success",
      "message" : ""
    }, {
      "success" : true,
      "elapsedTime" : 59,
      "requestName" : "duplicate-user",
      "message" : ""
    }, {
      "success" : true,
      "elapsedTime" : 20,
      "requestName" : "invalid-age",
      "message" : ""
    }, {
      "success" : false,
      "elapsedTime" : 5,
      "requestName" : "invalid-email",
      "message" : "host.testcontainers.internal:35615 failed to respond"
    } ]
  }, {
    "success" : false,
    "elapsedTime" : 5,
    "operationName" : "GET /api/users/{email}",
    "testStepResults" : [ {
      "success" : false,
      "elapsedTime" : 3,
      "requestName" : "user-with-age-preference-false",
      "message" : "Broken pipe"
    }, {
      "success" : false,
      "elapsedTime" : 2,
      "requestName" : "user-with-age-preference-true",
      "message" : "Broken pipe"
    } ]

**Container Logs for Problem2:**

11:55:55.540 DEBUG 1 --- [    task-5] i.g.m.util.openapi.OpenAPITestRunner     : OpenAPI schema validation of response is successful !
11:55:55.540 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Response Content-Type: application/json
11:55:55.541 DEBUG 1 --- [    task-5] i.g.m.service.TestRunnerService          : Saving 3 responses with testCaseId 64f4744aba8aab6e454ea4a7-1-GET /api/users
11:55:55.548 DEBUG 1 --- [    task-5] i.g.m.service.TestRunnerService          : Saving 3 requests with testCaseId 64f4744aba8aab6e454ea4a7-1-GET /api/users
11:55:55.574 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Launching test run on http://host.testcontainers.internal:35615 for 4 request(s)
11:55:55.574 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Using customized endpoint url: http://host.testcontainers.internal:35615/api/users
11:55:55.575 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Adding header Content-Type to request
11:55:55.576 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Adding header Accept to request
11:55:55.586 DEBUG 1 --- [080-exec-3] i.github.microcks.web.TestController     : Getting TestResult with id 64f4744aba8aab6e454ea4a7
11:55:55.781 DEBUG 1 --- [    task-5] i.g.m.util.openapi.OpenAPITestRunner     : Response status code: 201
11:55:55.781 DEBUG 1 --- [    task-5] i.g.m.util.openapi.OpenAPITestRunner     : Response media-type is application/json
11:55:55.785 DEBUG 1 --- [    task-5] i.g.m.util.openapi.OpenAPITestRunner     : Response expected status code: 201
11:55:55.789 DEBUG 1 --- [    task-5] i.g.m.u.o.OpenAPISchemaValidator         : Guessing OpenAPI spec format is YAML
11:55:55.795 DEBUG 1 --- [    task-5] i.g.m.util.JsonSchemaValidator           : Setting namespace to http://localhost:8080/api/resources/ in Json schema loading configuration
11:55:55.803 DEBUG 1 --- [    task-5] i.g.m.util.openapi.OpenAPITestRunner     : OpenAPI schema validation of response is successful !
11:55:55.803 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Response Content-Type: application/json
11:55:55.803 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Using customized endpoint url: http://host.testcontainers.internal:35615/api/users
11:55:55.804 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Adding header Accept to request
11:55:55.804 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Adding header Content-Type to request
11:55:55.808 DEBUG 1 --- [080-exec-4] i.github.microcks.web.TestController     : Getting TestResult with id 64f4744aba8aab6e454ea4a7
11:55:55.865 DEBUG 1 --- [    task-5] i.g.m.util.openapi.OpenAPITestRunner     : Response status code: 400
11:55:55.865 DEBUG 1 --- [    task-5] i.g.m.util.openapi.OpenAPITestRunner     : Response media-type is application/problem+json
11:55:55.868 DEBUG 1 --- [    task-5] i.g.m.util.openapi.OpenAPITestRunner     : Response expected status code: 400
11:55:55.869 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Response Content-Type: application/problem+json
11:55:55.869 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Using customized endpoint url: http://host.testcontainers.internal:35615/api/users
11:55:55.869 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Adding header Content-Type to request
11:55:55.869 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Adding header Accept to request
11:55:55.890 DEBUG 1 --- [    task-5] i.g.m.util.openapi.OpenAPITestRunner     : Response status code: 400
11:55:55.890 DEBUG 1 --- [    task-5] i.g.m.util.openapi.OpenAPITestRunner     : Response media-type is application/problem+json
11:55:55.893 DEBUG 1 --- [    task-5] i.g.m.util.openapi.OpenAPITestRunner     : Response expected status code: 400
11:55:55.893 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Response Content-Type: application/problem+json
11:55:55.894 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Using customized endpoint url: http://host.testcontainers.internal:35615/api/users
11:55:55.894 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Adding header Content-Type to request
11:55:55.894 DEBUG 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : Adding header Accept to request
11:55:55.896 ERROR 1 --- [    task-5] i.g.m.util.test.HttpTestRunner           : IOException while executing request invalid-email on http://host.testcontainers.internal:35615

org.apache.hc.core5.http.NoHttpResponseException: host.testcontainers.internal:35615 failed to respond
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:301)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:175)
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218)
	at org.apache.hc.client5.http.impl.io.BasicHttpClientConnectionManager$InternalConnectionEndpoint.execute(BasicHttpClientConnectionManager.java:555)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:216)
	at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:116)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:188)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:93)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)
	at io.github.microcks.util.test.HttpTestRunner.runTest(HttpTestRunner.java:163)
	at io.github.microcks.util.test.HttpTestRunner.runTest(HttpTestRunner.java:62)
	at io.github.microcks.service.TestRunnerService.launchTestsInternal(TestRunnerService.java:175)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.util.concurrent.FutureUtils.lambda$toSupplier$0(FutureUtils.java:74)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by lbroudoux** [comment]
Hi @cloudbackenddev,

Thanks for opening this issue. Could you tell the Microcks "standard" version you used for successful schema conformance tests?

**Comment by cloudbackenddev** [comment]
Hi @lbroudoux, Thanks for responding. Iam using following docker image version (quay.io/microcks/microcks:1.7.1). Please let me know if you need any other details

**Comment by lbroudoux** [comment]
Problem number 2, tracked by #905 should now be fixed!

I was looking at your problem number 1 (mismatch between `application/json` and `application/problem+json` and did not resolve it. 

In my tests, I focused on `POST /api/users` operation only and I think the OpenAPI contract you attached contains something inconsistent as line 632 should be changed to `application/problem+json`.

That way, when I'm doing the test with `application/json` referenced in my client schema with server-side returning `application/problem+json`, I've got a failure with the following message: `Response Content-Type does not match the expected one. Expecting application/json but got application/problem+json`. That is the expected outcome and the result I get with different versions of Microcks (1.7.x and 1.8.x).

That way, when I'm doing the test with `application/problem+json` referenced in my client schema with server-side returning `application/problem+json`, it's a success. That is the expected outcome and the result I get with different versions of Microcks (1.7.x and 1.8.x).

Could you please re-check that point ? (maybe with the newer version of `microcks-uber:nightly` now that the other issue is fixed)

**Comment by lbroudoux** [comment]
Also it looks like your mock definitions of your `GET /api/users` operation are incomplete as `page` and `size` params don't have values for the 3 samples (`page1size2`, `page1size3` and `page2size2`)

**Comment by lbroudoux** [comment]
Thanks for the feedback!
As one of the first users of our new Testcontainers integration, would you be ok to share your thoughts on a quick call over Zoom or others?
