### ISSUE TITLE
Http based tests partially failed but didn't reach the target endpoint

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#905]
### Describe the bug

On `1.8.x` branch (or `nightly` container image), it appears that some tests maybe marked as failed with error messages like `localhost:8686 failed to respond`. The weird thing is that the host can be reached because previous samples in the same test case actually succeed, connecting tothe target host.

When inspecting the log on the server side, it appears that the request is never received: looks like a client side issue.

When using a previous version of Microcks, the test pass and we can see a successful connection for each and every sample within a test case.

### Expected behavior

Test results must be exactly the same that with previous versions of Microcks.

### Actual behavior

We observe different behaviors when inspecting the HTTP exchanges with a Man In The Middle tooling (TCPMon or TCP Tunnel).

In the previous version of Microcks, we saw one connection per HTTP request,
In the nightly version of Microcks, we see many HTTP requests sharing the same connection. The problem occurs when the HTTP test response returns something different from the `200` or `201` HTTP code.

For example, when having 4 test samples with the first one returning 201 and the 3 other ones returning 400, we saw the following behavior: 

* A first connection is issued with 2 HTTP requests sent
* 2 requests are received and handled on the server side, responses are sent back
* The second response is a `400` with `Connection: close` > so it closes the underlying connection

```
### REQUESTS


POST /rest/User+API/1.0.0/api/users HTTP/1.1
Content-Type: application/json
Accept: application/json
Accept-Encoding: gzip, x-gzip, deflate
Content-Length: 50
Host: localhost:8686
Connection: keep-alive
User-Agent: Apache-HttpClient/5.2.1 (Java/17.0.6)

{"name":"alice","age":25,"email":"alice@test.com"}

POST /rest/User+API/1.0.0/api/users HTTP/1.1
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip, x-gzip, deflate
Content-Length: 46
Host: localhost:8686
Connection: keep-alive
User-Agent: Apache-HttpClient/5.2.1 (Java/17.0.6)

{"name":"pre","age":19,"email":"pre@test.com"}

### RESPONSES

HTTP/1.1 201 
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Type: application/json;charset=UTF-8
Content-Length: 148
Date: Mon, 04 Sep 2023 09:06:28 GMT
Keep-Alive: timeout=60
Connection: keep-alive

{"id":92,"name":"alice","age":25,"email":"alice@test.com","createdAt":"2023-09-03T03:26:36.664922900Z","updatedAt":"2023-09-03T03:26:36.664922900Z"}HTTP/1.1 400 
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Type: application/json;charset=UTF-8
Content-Length: 235
Date: Mon, 04 Sep 2023 09:06:28 GMT
Connection: close

{"type":"about:blank","title":"duplicate user","status":400,"detail":"cannot create duplicate user, user with email: pre@test.com exists","instance":"/api/users","timestamp":"2023-08-31T16:49:38.024689600Z","x-correlation-id":"123456"}
```

* HTTP Client recreates a new connection to the target host and issues the next request
* Request is received and handled on the service side and it responds with a `400` with `Connection: close` > so it closes the underlying connection

```
### REQUESTS

POST /rest/User+API/1.0.0/api/users HTTP/1.1
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip, x-gzip, deflate
Content-Length: 46
Host: localhost:8686
Connection: keep-alive
User-Agent: Apache-HttpClient/5.2.1 (Java/17.0.6)

{"name":"ved","age":17,"email":"ved@test.com"}

POST /rest/User+API/1.0.0/api/users HTTP/1.1
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip, x-gzip, deflate
Content-Length: 45
Host: localhost:8686
Connection: keep-alive
User-Agent: Apache-HttpClient/5.2.1 (Java/17.0.6)

{"name":"ved","age":19,"email":"vedtest.com"}

### RESPONSES

HTTP/1.1 400 
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Type: application/json;charset=UTF-8
Content-Length: 190
Date: Mon, 04 Sep 2023 09:06:28 GMT
Connection: close

{"type":"about:blank","title":"Bad Request","status":400,"detail":"Invalid request content.","instance":"/api/users","timestamp":"2023-08-31T16:44:27.507473300Z","x-correlation-id":"123456"}
``` 

On sending the last `POST` request, it fails on client-side with the following stack-trace:

```
12:51:26.852 DEBUG 88180 --- [    task-1] i.g.m.util.test.HttpTestRunner           : Sending following request content: {"name":"ved","age":19,"email":"vedtest.com"}
12:51:26.856 ERROR 88180 --- [    task-1] i.g.m.util.test.HttpTestRunner           : IOException while executing request invalid-email on http://localhost:8686/rest/User+API/1.0.0/api/users

org.apache.hc.core5.http.NoHttpResponseException: localhost:8686 failed to respond
        at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:301)
        at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:175)
        at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218)
        at org.apache.hc.client5.http.impl.io.BasicHttpClientConnectionManager$InternalConnectionEndpoint.execute(BasicHttpClientConnectionManager.java:555)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:216)
        at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:116)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:188)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:93)
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)
        at io.github.microcks.util.test.HttpTestRunner.runTest(HttpTestRunner.java:163)
        at io.github.microcks.util.test.HttpTestRunner.runTest(HttpTestRunner.java:62)
        at io.github.microcks.service.TestRunnerService.launchTestsInternal(TestRunnerService.java:182)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at org.springframework.util.concurrent.FutureUtils.lambda$toSupplier$0(FutureUtils.java:74)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

```

### Microcks version or git rev

Branch 1.8.x

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

**Comment by lbroudoux** [comment]
This regression is due to our migration from HTTP Client 4.5 to HTTP Client 5.2 that was forced when upgrading the Spring Boot version to 3.1.1 (see #840 and [this commit](https://github.com/microcks/microcks/commit/1b23b25eeb56a6a3abee5c711800e99fb577ebb2#diff-c8da592d2354ac1646b816dee7f7719fa41e67910aa395bd2c4a666698f4b9cb)).

The `BasicHttpClientConnectionManager` now has different behavior and reuses the same underlying connection for different HTTP requests and seems to fail to re-create a connection a second time... Switching to the `PoolingHttpClientConnectionManager` makes this problem disappear. We're now back on the same behavior as previous versions (e.g. one request per connection which looks like an excellent way to isolate things and avoid disturbance).

**Comment by lbroudoux** [comment]
Should now be fixed and available in `microcks:nightly` images.
