### ISSUE TITLE
White screen on fresh helm install

### ISSUE THREAD

**Issue by Gatonkage** [microcks/microcks#951]
### Describe the bug

After installing microcks version 1.8.0 via helm, users can login to microcks web interface however can only see a white screen. Seemingly caused by a 500 http error on /api/features/config request which normally responses a json config file.

### Expected behavior

Successful login to dashboard

### Actual behavior

A white screen is shown after successful login with admin,manager and user.

### How to Reproduce?

Used Rancher as the environment.
Added helm repo via url given in docs.
updated microcks and keycloak url values to locally resolvable FQDNs.
Installed the chart with command:
`helm install --namespace=microcks --timeout=2m20s --values=/home/shell/helm/values-microcks-1.8.0.yaml --version=1.8.0 --wait=true microcks`
Logged in to keycloak admin interface to ensure its working,
Logged in to microcks application, which showed only a white screen.

### Microcks version or git rev

1.8.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

helm chart

### Additional information

Helm chart takes docker image versions statically, helm chart version does not affect the images used. Can happily provide more granular information if needed.

**Comment by lbroudoux** [comment]
Thanks for raising this issue.
Can you please provide details on your Kecyloak settings: do you enable or disable it? Are you using both `url` and `privateUrl` to reach out Keycloak or just a public one? Currently restarting my minikube environment to check it out.

**Comment by lbroudoux** [comment]
I test it on my minikube cluster and could not reproduce it. FYI, I've added the following line from the `/install/kubernetes` folder on main branch.

```sh
helm install microcks ./microcks --namespace microcks3 --set microcks.url=microcks.m3.minikube.local --set keycloak.url=keycloak.m3.minikube.local --set keycloak.privateUrl=http://microcks-keycloak.microcks3.svc.cluster.local:8080
```

Here, I'm using `--set keycloak.privateUrl` as my Keycloak URL cannot be reached from within the cluster, so I use a direct connection using the Kube service name.

**Comment by Gatonkage** [comment]
Thank you for fast response. Keycloak is enabled with its default configuration and I only used url, haven't set privateUrl. but the url is resolvable and I could confirm that keycloak is working as intended:
- wrong passwords were rejected
- correct password gave an authorization bearer token
- moreover the mentioned /api/features/config url can be accessed from both my chrome and the microcks container/pod.

That said, when used with `privateUrl`, all worked like a charm. thank you.
I still find this a bit awkward but can see why it worked.

**Comment by lbroudoux** [comment]
Did you succeed in grabbing the log on the call to `/api/features/config` that was returning 500? I'd really like to understand what can go wrong there...

I'm still wondering why it could be related to security settings because as you see in [SecurityConfiguration](https://github.com/microcks/microcks/blob/master/webapp/src/main/java/io/github/microcks/config/SecurityConfiguration.java#L61) this URL is not protected (like the `/api/keycloak/config` that is also called during the bootstrap/authent process on client-side...).

**Comment by lbroudoux** [comment]
HI @Gatonkage,

Any news on this one?

**Comment by Gatonkage** [comment]
Hello there, sorry for taking sos long to answer, could not find time to re-install. Here is what I got: a screenshot taken right after the said login request and logs from microcks deployment. Keycloak deployment logs were completely unrelated so I did not save those.

- What I found (and could not catch last time) is that microcks deployment is having SSL trust issues.

![microcks white screen](https://github.com/microcks/microcks/assets/47725962/4222c919-9369-4b21-85d6-092d2153b63c)

- and here is the logs :
[microcks-spring.log](https://github.com/microcks/microcks/files/13349504/microcks-5d575d9df4-bwqtt_spring.log)

tried to remove any private & unrelated info from logs and the image. The application is up and running, I can provide more information, just describe what you need more, if that's the case.

**Comment by oliviernguyenquoc** [comment]
I re-open this issue because I got exactly the same one.

On a fresh install 
```
helm install microcks microcks/microcks --version 1.9.0 --namespace microcks --set microcks.url=microcks.$(minikube ip).xip.io --set keycloak.url=keycloak.$(minikube ip).xip.io
```

I use the default login/password: admin/microks123
And got the white screen

I have also tried:
```
helm install microcks microcks/microcks --version 1.9.0 --namespace microcks --set microcks.url=microcks.$(minikube ip).xip.io --set keycloak.url=keycloak.$(minikube ip).xip.io --set keycloak.privateUrl=http://microcks-keycloak.microcks.svc.cluster.local:8080
```

This is the logs:
<details>
  <summary>kubectl logs -n microcks microcks-5db7686744-8qsxx</summary>

exec java -XX:+TieredCompilation -XX:TieredStopAtLevel=2 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar
Picked up JAVA_TOOL_OPTIONS: -javaagent:/opt/opentelemetry-javaagent.jar
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2024-04-14 14:16:52:134 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.32.0

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.2.1)

14:16:52.995 [INFO] io.github.microcks.MicrocksApplication - Starting MicrocksApplication using Java 17.0.10 with PID 1 (/deployments/app.jar started by ? in /deployments)
14:16:52.999 [INFO] io.github.microcks.MicrocksApplication - The following 1 profile is active: "prod"
14:16:55.054 [INFO] io.github.microcks.config.WebConfiguration - Starting web application configuration, using profiles: [prod]
14:16:55.056 [INFO] io.github.microcks.config.WebConfiguration - Web application fully configured
14:16:55.284 [INFO] org.mongodb.driver.client - MongoClient with metadata {"driver": {"name": "mongo-java-driver|sync|spring-boot", "version": "4.11.1"}, "os": {"type": "Linux", "name": "Linux", "architecture": "amd64", "version": "6.8.0-76060800daily20240311-generic"}, "platform": "Java/Red Hat, Inc./17.0.10+7-LTS"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=MongoCredential{mechanism=null, userName='userM', source='microcks', password=<hidden>, mechanismProperties=<hidden>}, transportSettings=null, streamFactoryFactory=null, commandListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsCommandListener@618f627b], codecRegistry=ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, CollectionCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.client.model.mql.ExpressionCodecProvider@54e0f76f, com.mongodb.Jep395RecordCodecProvider@3fe8ad3f, com.mongodb.KotlinCodecProvider@7462ba4b]}, loggerSettings=LoggerSettings{maxDocumentLength=1000}, clusterSettings={hosts=[microcks-mongodb:27017], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[]', serverSelectionTimeout='30000 ms', localThreshold='15 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsConnectionPoolListener@31693a86], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=JAVA_LEGACY, serverApi=null, autoEncryptionSettings=null, dnsClient=null, inetAddressResolver=null, contextProvider=null}
14:16:55.306 [INFO] org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=microcks-mongodb:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=6, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=29951158}
14:17:01.762 [INFO] io.github.microcks.util.grpc.GrpcServerStarter - GRPC Server started on port 9090
14:17:02.021 [INFO] io.github.microcks.config.AICopilotConfiguration - AICopilot is disabled
14:17:02.360 [INFO] io.github.microcks.config.SecurityConfiguration - Starting security configuration for mocks
14:17:02.393 [INFO] io.github.microcks.config.SecurityConfiguration - Starting security configuration for APIs
14:17:02.394 [INFO] io.github.microcks.config.SecurityConfiguration - Keycloak is enabled, configuring oauth2 & request authorization
14:17:02.858 [INFO] io.github.microcks.MicrocksApplication - Started MicrocksApplication in 10.284 seconds (process running for 10.822)
14:20:32.814 [ERROR] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
org.springframework.security.authentication.AuthenticationServiceException: An error occurred while attempting to decode the Jwt: Couldn't retrieve remote JWK set: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://microcks-keycloak.microcks.svc.cluster.local:8080/realms/microcks/protocol/openid-connect/certs": Connection timed out
        at org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationProvider.getJwt(JwtAuthenticationProvider.java:106)
        at org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationProvider.authenticate(JwtAuthenticationProvider.java:88)
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)
        at org.springframework.security.authentication.ObservationAuthenticationManager.lambda$authenticate$1(ObservationAuthenticationManager.java:54)
        at io.micrometer.observation.Observation.observe(Observation.java:565)
        at org.springframework.security.authentication.ObservationAuthenticationManager.authenticate(ObservationAuthenticationManager.java:53)
        at org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:137)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240)
        at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323)
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224)
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
        at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195)
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
        at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
        at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:225)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:735)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.springframework.security.oauth2.jwt.JwtException: An error occurred while attempting to decode the Jwt: Couldn't retrieve remote JWK set: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://microcks-keycloak.microcks.svc.cluster.local:8080/realms/microcks/protocol/openid-connect/certs": Connection timed out
        at org.springframework.security.oauth2.jwt.NimbusJwtDecoder.createJwt(NimbusJwtDecoder.java:173)
        at org.springframework.security.oauth2.jwt.NimbusJwtDecoder.decode(NimbusJwtDecoder.java:138)
        at org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationProvider.getJwt(JwtAuthenticationProvider.java:99)
        ... 81 common frames omitted
Caused by: com.nimbusds.jose.RemoteKeySourceException: Couldn't retrieve remote JWK set: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://microcks-keycloak.microcks.svc.cluster.local:8080/realms/microcks/protocol/openid-connect/certs": Connection timed out
        at com.nimbusds.jose.jwk.source.RemoteJWKSet.updateJWKSetFromURL(RemoteJWKSet.java:307)
        at com.nimbusds.jose.jwk.source.RemoteJWKSet.get(RemoteJWKSet.java:437)
        at com.nimbusds.jose.proc.JWSVerificationKeySelector.selectJWSKeys(JWSVerificationKeySelector.java:157)
        at com.nimbusds.jwt.proc.DefaultJWTProcessor.selectKeys(DefaultJWTProcessor.java:283)
        at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:354)
        at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:303)
        at org.springframework.security.oauth2.jwt.NimbusJwtDecoder.createJwt(NimbusJwtDecoder.java:158)
        ... 83 common frames omitted
Caused by: java.io.IOException: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://microcks-keycloak.microcks.svc.cluster.local:8080/realms/microcks/protocol/openid-connect/certs": Connection timed out
        at org.springframework.security.oauth2.jwt.NimbusJwtDecoder$JwkSetUriJwtDecoderBuilder$RestOperationsResourceRetriever.getResponse(NimbusJwtDecoder.java:491)
        at org.springframework.security.oauth2.jwt.NimbusJwtDecoder$JwkSetUriJwtDecoderBuilder$RestOperationsResourceRetriever.retrieveResource(NimbusJwtDecoder.java:478)
        at com.nimbusds.jose.jwk.source.RemoteJWKSet.updateJWKSetFromURL(RemoteJWKSet.java:305)
        ... 89 common frames omitted
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://microcks-keycloak.microcks.svc.cluster.local:8080/realms/microcks/protocol/openid-connect/certs": Connection timed out
        at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:905)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:885)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:721)
        at org.springframework.security.oauth2.jwt.NimbusJwtDecoder$JwkSetUriJwtDecoderBuilder$RestOperationsResourceRetriever.getResponse(NimbusJwtDecoder.java:488)
        ... 91 common frames omitted
Caused by: java.net.ConnectException: Connection timed out
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        at java.base/sun.nio.ch.Net.connect(Net.java:568)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/java.net.Socket.connect(Socket.java:583)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:281)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
        at org.springframework.http.client.SimpleClientHttpRequest.executeInternal(SimpleClientHttpRequest.java:79)
        at org.springframework.http.client.AbstractStreamingClientHttpRequest.executeInternal(AbstractStreamingClientHttpRequest.java:70)
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:879)
        ... 93 common frames omitted
</details>

Any idea ?

**Comment by lbroudoux** [comment]
Hey there!

I tried re-installing everything on my Mac with a fresh minikube following the blog post here: https://microcks.io/blog/microcks-on-minikube/ and unfortunately, I cannot reproduce this... But I want to understand what can go wrong! I'll post just after a few things that can be checked to find the origin or your problem.

Let's see if we can solve this together...

**Comment by lbroudoux** [comment]
First, check the service is there and bound to a Keycloak pod:

```sh
$ kc describe svc/microcks-keycloak -n microcks
Name:              microcks-keycloak
Namespace:         microcks
Labels:            app=microcks
                   app.kubernetes.io/managed-by=Helm
                   container=keycloak
                   group=microcks
Annotations:       meta.helm.sh/release-name: microcks
                   meta.helm.sh/release-namespace: microcks
Selector:          app=microcks,container=keycloak,group=microcks
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.106.13.115
IPs:               10.106.13.115
Port:              keycloak  8080/TCP
TargetPort:        8080/TCP
Endpoints:         10.244.0.12:8080
Session Affinity:  None
Events:            <none>
```

Can you access the Keycloak UI using `keycloak.$(minikube ip).xip.io` in your browser? 
Can you ssh a pod in the same namespace or other and try to `curl http://microcks-keycloak.microcks.svc.cluster.local:8080` to see if you actually access the pod?

**Comment by lbroudoux** [comment]
Then you can also check that the config is correctly created, with these commands:

```shell
$ kc describe cm/microcks-config -n microcks | grep keycloak.
spring.security.oauth2.client.registration.keycloak.client-id=microcks-app
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_URL}/realms/${keycloak.realm}
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.resourceserver.jwt.issuer-uri=${sso.public-url}/realms/${keycloak.realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_URL}/realms/${keycloak.realm}/protocol/openid-connect/certs
keycloak.auth-server-url=${KEYCLOAK_URL}
keycloak.realm=microcks
keycloak.resource=microcks-app
keycloak.use-resource-role-mappings=true
keycloak.bearer-only=true
keycloak.ssl-required=external
keycloak.disable-trust-manager=true
sso.public-url=${KEYCLOAK_PUBLIC_URL:${keycloak.auth-server-url}}
```
and 
```shell
$ kc describe deployment/microcks -n microcks | grep KEYCLOAK
      KEYCLOAK_ENABLED:              true
      KEYCLOAK_URL:                  http://microcks-keycloak.microcks.svc.cluster.local:8080
      KEYCLOAK_PUBLIC_URL:           https://keycloak.m.minikube.local
```

Check that the keycloak urls are correctly in both configmap properties and deployment env variables.

**Comment by oliviernguyenquoc** [comment]
I just dig with what you suggest.

It seems that it works with version 1.9.0.

I had to modify a non-microcks configuration file by commenting a search entry line in /etc/resolv.conf:
`# search numericable.fr`

My honest guess is that this is what screwed up DNS resolutions.

Sorry for this non-microcks related mistake.

**Comment by lbroudoux** [comment]
No worries!

"It's always DNS!" 😆
